/**
 * ISO-3166 country dataset — the single source of truth.
 *
 * Every ISO-3166-1 alpha-2 code resolves to a {locale, currency, unitSystem,
 * timezone, language, name} profile. Adding a country is a data change here,
 * never a code change elsewhere. Currency and language codes are ISO-4217 /
 * BCP-47 strings — the app never assumes a closed union.
 *
 * Data is embedded so the app works offline and in SSR/edge runtimes.
 * Timezone is a best-guess primary IANA zone for the country; multi-zone
 * countries (US, RU, BR, ...) get their most populous zone. This is
 * good-enough default behavior; users can override via profile settings.
 */

export interface CountryRow {
  /** ISO-3166-1 alpha-2 uppercase. */
  code: string;
  /** English display name. */
  name: string;
  /** Primary BCP-47 language subtag (e.g. "en", "it"). */
  language: string;
  /** Full BCP-47 locale (e.g. "en-GB", "it-IT"). */
  locale: string;
  /** ISO-4217 currency code. */
  currency: string;
  /** Measurement system used for cooking/quantities. */
  unitSystem: "metric" | "imperial";
  /** Primary IANA timezone. */
  timezone: string;
}

/* eslint-disable prettier/prettier */
export const COUNTRY_ROWS: CountryRow[] = [
  { code: "AD", name: "Andorra", language: "ca", locale: "ca-AD", currency: "EUR", unitSystem: "metric", timezone: "Europe/Andorra" },
  { code: "AE", name: "United Arab Emirates", language: "ar", locale: "ar-AE", currency: "AED", unitSystem: "metric", timezone: "Asia/Dubai" },
  { code: "AF", name: "Afghanistan", language: "ps", locale: "ps-AF", currency: "AFN", unitSystem: "metric", timezone: "Asia/Kabul" },
  { code: "AG", name: "Antigua and Barbuda", language: "en", locale: "en-AG", currency: "XCD", unitSystem: "imperial", timezone: "America/Antigua" },
  { code: "AI", name: "Anguilla", language: "en", locale: "en-AI", currency: "XCD", unitSystem: "imperial", timezone: "America/Anguilla" },
  { code: "AL", name: "Albania", language: "sq", locale: "sq-AL", currency: "ALL", unitSystem: "metric", timezone: "Europe/Tirane" },
  { code: "AM", name: "Armenia", language: "hy", locale: "hy-AM", currency: "AMD", unitSystem: "metric", timezone: "Asia/Yerevan" },
  { code: "AO", name: "Angola", language: "pt", locale: "pt-AO", currency: "AOA", unitSystem: "metric", timezone: "Africa/Luanda" },
  { code: "AR", name: "Argentina", language: "es", locale: "es-AR", currency: "ARS", unitSystem: "metric", timezone: "America/Argentina/Buenos_Aires" },
  { code: "AT", name: "Austria", language: "de", locale: "de-AT", currency: "EUR", unitSystem: "metric", timezone: "Europe/Vienna" },
  { code: "AU", name: "Australia", language: "en", locale: "en-AU", currency: "AUD", unitSystem: "metric", timezone: "Australia/Sydney" },
  { code: "AW", name: "Aruba", language: "nl", locale: "nl-AW", currency: "AWG", unitSystem: "metric", timezone: "America/Aruba" },
  { code: "AZ", name: "Azerbaijan", language: "az", locale: "az-AZ", currency: "AZN", unitSystem: "metric", timezone: "Asia/Baku" },
  { code: "BA", name: "Bosnia and Herzegovina", language: "bs", locale: "bs-BA", currency: "BAM", unitSystem: "metric", timezone: "Europe/Sarajevo" },
  { code: "BB", name: "Barbados", language: "en", locale: "en-BB", currency: "BBD", unitSystem: "metric", timezone: "America/Barbados" },
  { code: "BD", name: "Bangladesh", language: "bn", locale: "bn-BD", currency: "BDT", unitSystem: "metric", timezone: "Asia/Dhaka" },
  { code: "BE", name: "Belgium", language: "nl", locale: "nl-BE", currency: "EUR", unitSystem: "metric", timezone: "Europe/Brussels" },
  { code: "BF", name: "Burkina Faso", language: "fr", locale: "fr-BF", currency: "XOF", unitSystem: "metric", timezone: "Africa/Ouagadougou" },
  { code: "BG", name: "Bulgaria", language: "bg", locale: "bg-BG", currency: "BGN", unitSystem: "metric", timezone: "Europe/Sofia" },
  { code: "BH", name: "Bahrain", language: "ar", locale: "ar-BH", currency: "BHD", unitSystem: "metric", timezone: "Asia/Bahrain" },
  { code: "BI", name: "Burundi", language: "fr", locale: "fr-BI", currency: "BIF", unitSystem: "metric", timezone: "Africa/Bujumbura" },
  { code: "BJ", name: "Benin", language: "fr", locale: "fr-BJ", currency: "XOF", unitSystem: "metric", timezone: "Africa/Porto-Novo" },
  { code: "BN", name: "Brunei", language: "ms", locale: "ms-BN", currency: "BND", unitSystem: "metric", timezone: "Asia/Brunei" },
  { code: "BO", name: "Bolivia", language: "es", locale: "es-BO", currency: "BOB", unitSystem: "metric", timezone: "America/La_Paz" },
  { code: "BR", name: "Brazil", language: "pt", locale: "pt-BR", currency: "BRL", unitSystem: "metric", timezone: "America/Sao_Paulo" },
  { code: "BS", name: "Bahamas", language: "en", locale: "en-BS", currency: "BSD", unitSystem: "imperial", timezone: "America/Nassau" },
  { code: "BT", name: "Bhutan", language: "dz", locale: "dz-BT", currency: "BTN", unitSystem: "metric", timezone: "Asia/Thimphu" },
  { code: "BW", name: "Botswana", language: "en", locale: "en-BW", currency: "BWP", unitSystem: "metric", timezone: "Africa/Gaborone" },
  { code: "BY", name: "Belarus", language: "be", locale: "be-BY", currency: "BYN", unitSystem: "metric", timezone: "Europe/Minsk" },
  { code: "BZ", name: "Belize", language: "en", locale: "en-BZ", currency: "BZD", unitSystem: "imperial", timezone: "America/Belize" },
  { code: "CA", name: "Canada", language: "en", locale: "en-CA", currency: "CAD", unitSystem: "metric", timezone: "America/Toronto" },
  { code: "CD", name: "DR Congo", language: "fr", locale: "fr-CD", currency: "CDF", unitSystem: "metric", timezone: "Africa/Kinshasa" },
  { code: "CF", name: "Central African Republic", language: "fr", locale: "fr-CF", currency: "XAF", unitSystem: "metric", timezone: "Africa/Bangui" },
  { code: "CG", name: "Congo", language: "fr", locale: "fr-CG", currency: "XAF", unitSystem: "metric", timezone: "Africa/Brazzaville" },
  { code: "CH", name: "Switzerland", language: "de", locale: "de-CH", currency: "CHF", unitSystem: "metric", timezone: "Europe/Zurich" },
  { code: "CI", name: "Ivory Coast", language: "fr", locale: "fr-CI", currency: "XOF", unitSystem: "metric", timezone: "Africa/Abidjan" },
  { code: "CL", name: "Chile", language: "es", locale: "es-CL", currency: "CLP", unitSystem: "metric", timezone: "America/Santiago" },
  { code: "CM", name: "Cameroon", language: "fr", locale: "fr-CM", currency: "XAF", unitSystem: "metric", timezone: "Africa/Douala" },
  { code: "CN", name: "China", language: "zh", locale: "zh-CN", currency: "CNY", unitSystem: "metric", timezone: "Asia/Shanghai" },
  { code: "CO", name: "Colombia", language: "es", locale: "es-CO", currency: "COP", unitSystem: "metric", timezone: "America/Bogota" },
  { code: "CR", name: "Costa Rica", language: "es", locale: "es-CR", currency: "CRC", unitSystem: "metric", timezone: "America/Costa_Rica" },
  { code: "CU", name: "Cuba", language: "es", locale: "es-CU", currency: "CUP", unitSystem: "metric", timezone: "America/Havana" },
  { code: "CV", name: "Cape Verde", language: "pt", locale: "pt-CV", currency: "CVE", unitSystem: "metric", timezone: "Atlantic/Cape_Verde" },
  { code: "CY", name: "Cyprus", language: "el", locale: "el-CY", currency: "EUR", unitSystem: "metric", timezone: "Asia/Nicosia" },
  { code: "CZ", name: "Czechia", language: "cs", locale: "cs-CZ", currency: "CZK", unitSystem: "metric", timezone: "Europe/Prague" },
  { code: "DE", name: "Germany", language: "de", locale: "de-DE", currency: "EUR", unitSystem: "metric", timezone: "Europe/Berlin" },
  { code: "DJ", name: "Djibouti", language: "fr", locale: "fr-DJ", currency: "DJF", unitSystem: "metric", timezone: "Africa/Djibouti" },
  { code: "DK", name: "Denmark", language: "da", locale: "da-DK", currency: "DKK", unitSystem: "metric", timezone: "Europe/Copenhagen" },
  { code: "DM", name: "Dominica", language: "en", locale: "en-DM", currency: "XCD", unitSystem: "metric", timezone: "America/Dominica" },
  { code: "DO", name: "Dominican Republic", language: "es", locale: "es-DO", currency: "DOP", unitSystem: "metric", timezone: "America/Santo_Domingo" },
  { code: "DZ", name: "Algeria", language: "ar", locale: "ar-DZ", currency: "DZD", unitSystem: "metric", timezone: "Africa/Algiers" },
  { code: "EC", name: "Ecuador", language: "es", locale: "es-EC", currency: "USD", unitSystem: "metric", timezone: "America/Guayaquil" },
  { code: "EE", name: "Estonia", language: "et", locale: "et-EE", currency: "EUR", unitSystem: "metric", timezone: "Europe/Tallinn" },
  { code: "EG", name: "Egypt", language: "ar", locale: "ar-EG", currency: "EGP", unitSystem: "metric", timezone: "Africa/Cairo" },
  { code: "ER", name: "Eritrea", language: "ti", locale: "ti-ER", currency: "ERN", unitSystem: "metric", timezone: "Africa/Asmara" },
  { code: "ES", name: "Spain", language: "es", locale: "es-ES", currency: "EUR", unitSystem: "metric", timezone: "Europe/Madrid" },
  { code: "ET", name: "Ethiopia", language: "am", locale: "am-ET", currency: "ETB", unitSystem: "metric", timezone: "Africa/Addis_Ababa" },
  { code: "FI", name: "Finland", language: "fi", locale: "fi-FI", currency: "EUR", unitSystem: "metric", timezone: "Europe/Helsinki" },
  { code: "FJ", name: "Fiji", language: "en", locale: "en-FJ", currency: "FJD", unitSystem: "metric", timezone: "Pacific/Fiji" },
  { code: "FR", name: "France", language: "fr", locale: "fr-FR", currency: "EUR", unitSystem: "metric", timezone: "Europe/Paris" },
  { code: "GA", name: "Gabon", language: "fr", locale: "fr-GA", currency: "XAF", unitSystem: "metric", timezone: "Africa/Libreville" },
  { code: "GB", name: "United Kingdom", language: "en", locale: "en-GB", currency: "GBP", unitSystem: "metric", timezone: "Europe/London" },
  { code: "GD", name: "Grenada", language: "en", locale: "en-GD", currency: "XCD", unitSystem: "metric", timezone: "America/Grenada" },
  { code: "GE", name: "Georgia", language: "ka", locale: "ka-GE", currency: "GEL", unitSystem: "metric", timezone: "Asia/Tbilisi" },
  { code: "GH", name: "Ghana", language: "en", locale: "en-GH", currency: "GHS", unitSystem: "metric", timezone: "Africa/Accra" },
  { code: "GN", name: "Guinea", language: "fr", locale: "fr-GN", currency: "GNF", unitSystem: "metric", timezone: "Africa/Conakry" },
  { code: "GR", name: "Greece", language: "el", locale: "el-GR", currency: "EUR", unitSystem: "metric", timezone: "Europe/Athens" },
  { code: "GT", name: "Guatemala", language: "es", locale: "es-GT", currency: "GTQ", unitSystem: "metric", timezone: "America/Guatemala" },
  { code: "GY", name: "Guyana", language: "en", locale: "en-GY", currency: "GYD", unitSystem: "metric", timezone: "America/Guyana" },
  { code: "HK", name: "Hong Kong", language: "zh", locale: "zh-HK", currency: "HKD", unitSystem: "metric", timezone: "Asia/Hong_Kong" },
  { code: "HN", name: "Honduras", language: "es", locale: "es-HN", currency: "HNL", unitSystem: "metric", timezone: "America/Tegucigalpa" },
  { code: "HR", name: "Croatia", language: "hr", locale: "hr-HR", currency: "EUR", unitSystem: "metric", timezone: "Europe/Zagreb" },
  { code: "HT", name: "Haiti", language: "fr", locale: "fr-HT", currency: "HTG", unitSystem: "metric", timezone: "America/Port-au-Prince" },
  { code: "HU", name: "Hungary", language: "hu", locale: "hu-HU", currency: "HUF", unitSystem: "metric", timezone: "Europe/Budapest" },
  { code: "ID", name: "Indonesia", language: "id", locale: "id-ID", currency: "IDR", unitSystem: "metric", timezone: "Asia/Jakarta" },
  { code: "IE", name: "Ireland", language: "en", locale: "en-IE", currency: "EUR", unitSystem: "metric", timezone: "Europe/Dublin" },
  { code: "IL", name: "Israel", language: "he", locale: "he-IL", currency: "ILS", unitSystem: "metric", timezone: "Asia/Jerusalem" },
  { code: "IN", name: "India", language: "hi", locale: "hi-IN", currency: "INR", unitSystem: "metric", timezone: "Asia/Kolkata" },
  { code: "IQ", name: "Iraq", language: "ar", locale: "ar-IQ", currency: "IQD", unitSystem: "metric", timezone: "Asia/Baghdad" },
  { code: "IR", name: "Iran", language: "fa", locale: "fa-IR", currency: "IRR", unitSystem: "metric", timezone: "Asia/Tehran" },
  { code: "IS", name: "Iceland", language: "is", locale: "is-IS", currency: "ISK", unitSystem: "metric", timezone: "Atlantic/Reykjavik" },
  { code: "IT", name: "Italy", language: "it", locale: "it-IT", currency: "EUR", unitSystem: "metric", timezone: "Europe/Rome" },
  { code: "JM", name: "Jamaica", language: "en", locale: "en-JM", currency: "JMD", unitSystem: "metric", timezone: "America/Jamaica" },
  { code: "JO", name: "Jordan", language: "ar", locale: "ar-JO", currency: "JOD", unitSystem: "metric", timezone: "Asia/Amman" },
  { code: "JP", name: "Japan", language: "ja", locale: "ja-JP", currency: "JPY", unitSystem: "metric", timezone: "Asia/Tokyo" },
  { code: "KE", name: "Kenya", language: "sw", locale: "sw-KE", currency: "KES", unitSystem: "metric", timezone: "Africa/Nairobi" },
  { code: "KG", name: "Kyrgyzstan", language: "ky", locale: "ky-KG", currency: "KGS", unitSystem: "metric", timezone: "Asia/Bishkek" },
  { code: "KH", name: "Cambodia", language: "km", locale: "km-KH", currency: "KHR", unitSystem: "metric", timezone: "Asia/Phnom_Penh" },
  { code: "KR", name: "South Korea", language: "ko", locale: "ko-KR", currency: "KRW", unitSystem: "metric", timezone: "Asia/Seoul" },
  { code: "KW", name: "Kuwait", language: "ar", locale: "ar-KW", currency: "KWD", unitSystem: "metric", timezone: "Asia/Kuwait" },
  { code: "KZ", name: "Kazakhstan", language: "kk", locale: "kk-KZ", currency: "KZT", unitSystem: "metric", timezone: "Asia/Almaty" },
  { code: "LA", name: "Laos", language: "lo", locale: "lo-LA", currency: "LAK", unitSystem: "metric", timezone: "Asia/Vientiane" },
  { code: "LB", name: "Lebanon", language: "ar", locale: "ar-LB", currency: "LBP", unitSystem: "metric", timezone: "Asia/Beirut" },
  { code: "LK", name: "Sri Lanka", language: "si", locale: "si-LK", currency: "LKR", unitSystem: "metric", timezone: "Asia/Colombo" },
  { code: "LR", name: "Liberia", language: "en", locale: "en-LR", currency: "LRD", unitSystem: "imperial", timezone: "Africa/Monrovia" },
  { code: "LS", name: "Lesotho", language: "en", locale: "en-LS", currency: "LSL", unitSystem: "metric", timezone: "Africa/Maseru" },
  { code: "LT", name: "Lithuania", language: "lt", locale: "lt-LT", currency: "EUR", unitSystem: "metric", timezone: "Europe/Vilnius" },
  { code: "LU", name: "Luxembourg", language: "fr", locale: "fr-LU", currency: "EUR", unitSystem: "metric", timezone: "Europe/Luxembourg" },
  { code: "LV", name: "Latvia", language: "lv", locale: "lv-LV", currency: "EUR", unitSystem: "metric", timezone: "Europe/Riga" },
  { code: "LY", name: "Libya", language: "ar", locale: "ar-LY", currency: "LYD", unitSystem: "metric", timezone: "Africa/Tripoli" },
  { code: "MA", name: "Morocco", language: "ar", locale: "ar-MA", currency: "MAD", unitSystem: "metric", timezone: "Africa/Casablanca" },
  { code: "MD", name: "Moldova", language: "ro", locale: "ro-MD", currency: "MDL", unitSystem: "metric", timezone: "Europe/Chisinau" },
  { code: "ME", name: "Montenegro", language: "sr", locale: "sr-ME", currency: "EUR", unitSystem: "metric", timezone: "Europe/Podgorica" },
  { code: "MG", name: "Madagascar", language: "fr", locale: "fr-MG", currency: "MGA", unitSystem: "metric", timezone: "Indian/Antananarivo" },
  { code: "MK", name: "North Macedonia", language: "mk", locale: "mk-MK", currency: "MKD", unitSystem: "metric", timezone: "Europe/Skopje" },
  { code: "ML", name: "Mali", language: "fr", locale: "fr-ML", currency: "XOF", unitSystem: "metric", timezone: "Africa/Bamako" },
  { code: "MM", name: "Myanmar", language: "my", locale: "my-MM", currency: "MMK", unitSystem: "metric", timezone: "Asia/Yangon" },
  { code: "MN", name: "Mongolia", language: "mn", locale: "mn-MN", currency: "MNT", unitSystem: "metric", timezone: "Asia/Ulaanbaatar" },
  { code: "MO", name: "Macao", language: "zh", locale: "zh-MO", currency: "MOP", unitSystem: "metric", timezone: "Asia/Macau" },
  { code: "MR", name: "Mauritania", language: "ar", locale: "ar-MR", currency: "MRU", unitSystem: "metric", timezone: "Africa/Nouakchott" },
  { code: "MT", name: "Malta", language: "mt", locale: "mt-MT", currency: "EUR", unitSystem: "metric", timezone: "Europe/Malta" },
  { code: "MU", name: "Mauritius", language: "en", locale: "en-MU", currency: "MUR", unitSystem: "metric", timezone: "Indian/Mauritius" },
  { code: "MV", name: "Maldives", language: "dv", locale: "dv-MV", currency: "MVR", unitSystem: "metric", timezone: "Indian/Maldives" },
  { code: "MW", name: "Malawi", language: "en", locale: "en-MW", currency: "MWK", unitSystem: "metric", timezone: "Africa/Blantyre" },
  { code: "MX", name: "Mexico", language: "es", locale: "es-MX", currency: "MXN", unitSystem: "metric", timezone: "America/Mexico_City" },
  { code: "MY", name: "Malaysia", language: "ms", locale: "ms-MY", currency: "MYR", unitSystem: "metric", timezone: "Asia/Kuala_Lumpur" },
  { code: "MZ", name: "Mozambique", language: "pt", locale: "pt-MZ", currency: "MZN", unitSystem: "metric", timezone: "Africa/Maputo" },
  { code: "NA", name: "Namibia", language: "en", locale: "en-NA", currency: "NAD", unitSystem: "metric", timezone: "Africa/Windhoek" },
  { code: "NE", name: "Niger", language: "fr", locale: "fr-NE", currency: "XOF", unitSystem: "metric", timezone: "Africa/Niamey" },
  { code: "NG", name: "Nigeria", language: "en", locale: "en-NG", currency: "NGN", unitSystem: "metric", timezone: "Africa/Lagos" },
  { code: "NI", name: "Nicaragua", language: "es", locale: "es-NI", currency: "NIO", unitSystem: "metric", timezone: "America/Managua" },
  { code: "NL", name: "Netherlands", language: "nl", locale: "nl-NL", currency: "EUR", unitSystem: "metric", timezone: "Europe/Amsterdam" },
  { code: "NO", name: "Norway", language: "no", locale: "no-NO", currency: "NOK", unitSystem: "metric", timezone: "Europe/Oslo" },
  { code: "NP", name: "Nepal", language: "ne", locale: "ne-NP", currency: "NPR", unitSystem: "metric", timezone: "Asia/Kathmandu" },
  { code: "NZ", name: "New Zealand", language: "en", locale: "en-NZ", currency: "NZD", unitSystem: "metric", timezone: "Pacific/Auckland" },
  { code: "OM", name: "Oman", language: "ar", locale: "ar-OM", currency: "OMR", unitSystem: "metric", timezone: "Asia/Muscat" },
  { code: "PA", name: "Panama", language: "es", locale: "es-PA", currency: "PAB", unitSystem: "metric", timezone: "America/Panama" },
  { code: "PE", name: "Peru", language: "es", locale: "es-PE", currency: "PEN", unitSystem: "metric", timezone: "America/Lima" },
  { code: "PG", name: "Papua New Guinea", language: "en", locale: "en-PG", currency: "PGK", unitSystem: "metric", timezone: "Pacific/Port_Moresby" },
  { code: "PH", name: "Philippines", language: "en", locale: "en-PH", currency: "PHP", unitSystem: "metric", timezone: "Asia/Manila" },
  { code: "PK", name: "Pakistan", language: "ur", locale: "ur-PK", currency: "PKR", unitSystem: "metric", timezone: "Asia/Karachi" },
  { code: "PL", name: "Poland", language: "pl", locale: "pl-PL", currency: "PLN", unitSystem: "metric", timezone: "Europe/Warsaw" },
  { code: "PT", name: "Portugal", language: "pt", locale: "pt-PT", currency: "EUR", unitSystem: "metric", timezone: "Europe/Lisbon" },
  { code: "PY", name: "Paraguay", language: "es", locale: "es-PY", currency: "PYG", unitSystem: "metric", timezone: "America/Asuncion" },
  { code: "QA", name: "Qatar", language: "ar", locale: "ar-QA", currency: "QAR", unitSystem: "metric", timezone: "Asia/Qatar" },
  { code: "RO", name: "Romania", language: "ro", locale: "ro-RO", currency: "RON", unitSystem: "metric", timezone: "Europe/Bucharest" },
  { code: "RS", name: "Serbia", language: "sr", locale: "sr-RS", currency: "RSD", unitSystem: "metric", timezone: "Europe/Belgrade" },
  { code: "RU", name: "Russia", language: "ru", locale: "ru-RU", currency: "RUB", unitSystem: "metric", timezone: "Europe/Moscow" },
  { code: "RW", name: "Rwanda", language: "rw", locale: "rw-RW", currency: "RWF", unitSystem: "metric", timezone: "Africa/Kigali" },
  { code: "SA", name: "Saudi Arabia", language: "ar", locale: "ar-SA", currency: "SAR", unitSystem: "metric", timezone: "Asia/Riyadh" },
  { code: "SC", name: "Seychelles", language: "en", locale: "en-SC", currency: "SCR", unitSystem: "metric", timezone: "Indian/Mahe" },
  { code: "SD", name: "Sudan", language: "ar", locale: "ar-SD", currency: "SDG", unitSystem: "metric", timezone: "Africa/Khartoum" },
  { code: "SE", name: "Sweden", language: "sv", locale: "sv-SE", currency: "SEK", unitSystem: "metric", timezone: "Europe/Stockholm" },
  { code: "SG", name: "Singapore", language: "en", locale: "en-SG", currency: "SGD", unitSystem: "metric", timezone: "Asia/Singapore" },
  { code: "SI", name: "Slovenia", language: "sl", locale: "sl-SI", currency: "EUR", unitSystem: "metric", timezone: "Europe/Ljubljana" },
  { code: "SK", name: "Slovakia", language: "sk", locale: "sk-SK", currency: "EUR", unitSystem: "metric", timezone: "Europe/Bratislava" },
  { code: "SL", name: "Sierra Leone", language: "en", locale: "en-SL", currency: "SLE", unitSystem: "metric", timezone: "Africa/Freetown" },
  { code: "SN", name: "Senegal", language: "fr", locale: "fr-SN", currency: "XOF", unitSystem: "metric", timezone: "Africa/Dakar" },
  { code: "SO", name: "Somalia", language: "so", locale: "so-SO", currency: "SOS", unitSystem: "metric", timezone: "Africa/Mogadishu" },
  { code: "SR", name: "Suriname", language: "nl", locale: "nl-SR", currency: "SRD", unitSystem: "metric", timezone: "America/Paramaribo" },
  { code: "SS", name: "South Sudan", language: "en", locale: "en-SS", currency: "SSP", unitSystem: "metric", timezone: "Africa/Juba" },
  { code: "SV", name: "El Salvador", language: "es", locale: "es-SV", currency: "USD", unitSystem: "metric", timezone: "America/El_Salvador" },
  { code: "SY", name: "Syria", language: "ar", locale: "ar-SY", currency: "SYP", unitSystem: "metric", timezone: "Asia/Damascus" },
  { code: "SZ", name: "Eswatini", language: "en", locale: "en-SZ", currency: "SZL", unitSystem: "metric", timezone: "Africa/Mbabane" },
  { code: "TD", name: "Chad", language: "fr", locale: "fr-TD", currency: "XAF", unitSystem: "metric", timezone: "Africa/Ndjamena" },
  { code: "TG", name: "Togo", language: "fr", locale: "fr-TG", currency: "XOF", unitSystem: "metric", timezone: "Africa/Lome" },
  { code: "TH", name: "Thailand", language: "th", locale: "th-TH", currency: "THB", unitSystem: "metric", timezone: "Asia/Bangkok" },
  { code: "TJ", name: "Tajikistan", language: "tg", locale: "tg-TJ", currency: "TJS", unitSystem: "metric", timezone: "Asia/Dushanbe" },
  { code: "TM", name: "Turkmenistan", language: "tk", locale: "tk-TM", currency: "TMT", unitSystem: "metric", timezone: "Asia/Ashgabat" },
  { code: "TN", name: "Tunisia", language: "ar", locale: "ar-TN", currency: "TND", unitSystem: "metric", timezone: "Africa/Tunis" },
  { code: "TR", name: "Turkey", language: "tr", locale: "tr-TR", currency: "TRY", unitSystem: "metric", timezone: "Europe/Istanbul" },
  { code: "TT", name: "Trinidad and Tobago", language: "en", locale: "en-TT", currency: "TTD", unitSystem: "metric", timezone: "America/Port_of_Spain" },
  { code: "TW", name: "Taiwan", language: "zh", locale: "zh-TW", currency: "TWD", unitSystem: "metric", timezone: "Asia/Taipei" },
  { code: "TZ", name: "Tanzania", language: "sw", locale: "sw-TZ", currency: "TZS", unitSystem: "metric", timezone: "Africa/Dar_es_Salaam" },
  { code: "UA", name: "Ukraine", language: "uk", locale: "uk-UA", currency: "UAH", unitSystem: "metric", timezone: "Europe/Kyiv" },
  { code: "UG", name: "Uganda", language: "en", locale: "en-UG", currency: "UGX", unitSystem: "metric", timezone: "Africa/Kampala" },
  { code: "US", name: "United States", language: "en", locale: "en-US", currency: "USD", unitSystem: "imperial", timezone: "America/New_York" },
  { code: "UY", name: "Uruguay", language: "es", locale: "es-UY", currency: "UYU", unitSystem: "metric", timezone: "America/Montevideo" },
  { code: "UZ", name: "Uzbekistan", language: "uz", locale: "uz-UZ", currency: "UZS", unitSystem: "metric", timezone: "Asia/Tashkent" },
  { code: "VE", name: "Venezuela", language: "es", locale: "es-VE", currency: "VES", unitSystem: "metric", timezone: "America/Caracas" },
  { code: "VN", name: "Vietnam", language: "vi", locale: "vi-VN", currency: "VND", unitSystem: "metric", timezone: "Asia/Ho_Chi_Minh" },
  { code: "YE", name: "Yemen", language: "ar", locale: "ar-YE", currency: "YER", unitSystem: "metric", timezone: "Asia/Aden" },
  { code: "ZA", name: "South Africa", language: "en", locale: "en-ZA", currency: "ZAR", unitSystem: "metric", timezone: "Africa/Johannesburg" },
  { code: "ZM", name: "Zambia", language: "en", locale: "en-ZM", currency: "ZMW", unitSystem: "metric", timezone: "Africa/Lusaka" },
  { code: "ZW", name: "Zimbabwe", language: "en", locale: "en-ZW", currency: "ZWL", unitSystem: "metric", timezone: "Africa/Harare" },
];
/* eslint-enable prettier/prettier */

/**
 * Common name / legacy alias → ISO α-2 code.
 * Consolidates the six historical `COUNTRY_ALIAS` tables that used to live
 * in `shopping-links`, `buy-online`, `product-search`, `price-data/…`,
 * `location/delivery-availability` and `price-data/supermarkets`.
 */
export const NAME_TO_ALPHA2: Record<string, string> = {
  // English names
  "united kingdom": "GB", "great britain": "GB", "britain": "GB", "uk": "GB", "gb": "GB", "england": "GB", "scotland": "GB", "wales": "GB",
  "united states": "US", "usa": "US", "america": "US",
  "united arab emirates": "AE", "uae": "AE", "emirates": "AE",
  "south korea": "KR", "korea": "KR",
  "russia": "RU", "russian federation": "RU",
  "czech republic": "CZ", "czechia": "CZ",
  "vietnam": "VN", "viet nam": "VN",
  "iran": "IR",
  "hong kong": "HK",
  // Localized names (headline markets)
  "italia": "IT", "italy": "IT",
  "deutschland": "DE", "germany": "DE",
  "españa": "ES", "espana": "ES", "spain": "ES",
  "france": "FR",
  "brasil": "BR", "brazil": "BR",
  "méxico": "MX", "mexico": "MX",
  "portugal": "PT",
  "nederland": "NL", "netherlands": "NL", "holland": "NL",
  "österreich": "AT", "austria": "AT",
  "schweiz": "CH", "suisse": "CH", "svizzera": "CH", "switzerland": "CH",
  "polska": "PL", "poland": "PL",
  "türkiye": "TR", "turkiye": "TR", "turkey": "TR",
  "日本": "JP", "japan": "JP",
  "中国": "CN", "china": "CN",
  "대한민국": "KR",
};
