/**
 * Nomi italiani dei prodotti del catalogo.
 *
 * PERCHÉ SERVE
 * ------------
 * Il catalogo prezzi e il motore pasti locale sono in inglese: la lista della
 * spesa mostrava "Mushrooms" e "Mixed salad greens" a un utente italiano, e
 * la ricerca del prezzo reale cercava "Mushrooms" su Google Shopping Italia —
 * da cui tornavano funghi essiccati, kit di coltivazione e integratori.
 *
 * Le traduzioni sono scritte come le userebbe una persona sulla lista della
 * spesa ("Passata di pomodoro", non "Salsa di pomodoro"), non tradotte alla
 * lettera. GENERATO: rigenerare con lo script se il catalogo cambia.
 *
 * 120 voci su 120 del catalogo.
 */

/** Chiave del catalogo → nome italiano. */
export const LABEL_BY_KEY: Record<string, string> = {
  beef_steak: "Bistecca di manzo",
  carrots_celery: "Carote e sedano",
  cereal: "Cereali da colazione",
  feta: "Feta",
  granola: "Granola",
  noodles: "Noodles",
  onions_garlic: "Cipolle e aglio",
  pesto: "Pesto",
  sourdough: "Pane a lievitazione naturale",
  almonds: "Mandorle",
  apples: "Mele",
  asparagus: "Asparagi",
  avocado: "Avocado",
  bacon: "Pancetta",
  balsamic_vinegar: "Aceto balsamico",
  bananas: "Banane",
  basmati_rice: "Riso basmati",
  beef_mince: "Macinato di manzo",
  bell_peppers: "Peperoni",
  black_beans: "Fagioli neri",
  black_pepper: "Pepe nero",
  blueberries: "Mirtilli",
  broccoli: "Broccoli",
  bulgur: "Bulgur",
  butter: "Burro",
  cabbage: "Cavolo",
  canned_tomatoes: "Pomodori pelati",
  capers: "Capperi",
  carrots: "Carote",
  cauliflower: "Cavolfiore",
  celery: "Sedano",
  cheddar: "Formaggio",
  cherry_tomatoes: "Pomodorini",
  chicken_breast: "Petto di pollo",
  chicken_thighs: "Cosce di pollo",
  chickpeas: "Ceci",
  cinnamon: "Cannella",
  coffee: "Caffè",
  corn: "Mais",
  couscous: "Couscous",
  cream: "Panna da cucina",
  cucumber: "Cetrioli",
  dried_herbs: "Erbe secche",
  eggplant: "Melanzane",
  eggs: "Uova",
  flour: "Farina",
  free_range_chicken: "Pollo ruspante",
  fresh_herbs: "Erbe aromatiche",
  garlic: "Aglio",
  grapes: "Uva",
  greek_yogurt: "Yogurt greco",
  green_beans: "Fagiolini",
  ham: "Prosciutto cotto",
  honey: "Miele",
  jam: "Marmellata",
  kale: "Cavolo nero",
  ketchup: "Ketchup",
  kidney_beans: "Fagioli rossi",
  leek: "Porri",
  lemons: "Limoni",
  mayo: "Maionese",
  melon: "Melone",
  milk: "Latte",
  mixed_nuts: "Frutta secca",
  mozzarella: "Mozzarella",
  mushrooms: "Funghi",
  mustard: "Senape",
  oats: "Fiocchi d'avena",
  olive_oil: "Olio extravergine di oliva",
  olives: "Olive",
  onions: "Cipolle",
  oranges: "Arance",
  paprika: "Paprika",
  parmesan: "Parmigiano",
  pasta: "Pasta",
  peaches: "Pesche",
  peanut_butter: "Burro di arachidi",
  pears: "Pere",
  peas: "Piselli",
  pita: "Pane pita",
  pizza_flour: "Farina per pizza",
  pork_loin: "Lonza di maiale",
  potatoes: "Patate",
  prawns: "Gamberetti",
  quinoa: "Quinoa",
  raspberries: "Lamponi",
  red_lentils: "Lenticchie rosse",
  rice: "Riso",
  ricotta: "Ricotta",
  rocket: "Rucola",
  salad_greens: "Insalata mista",
  salmon_fillet: "Filetto di salmone",
  salt: "Sale",
  sausages: "Salsicce",
  seasonal_veg: "Verdure di stagione",
  seeds: "Semi misti",
  soy_sauce: "Salsa di soia",
  spices: "Spezie",
  spinach: "Spinaci",
  stock_cubes: "Dado",
  strawberries: "Fragole",
  sugar: "Zucchero",
  sunflower_oil: "Olio di semi",
  sweet_potatoes: "Patate dolci",
  tahini: "Tahina",
  tea: "Tè",
  tofu: "Tofu",
  tomato_sauce: "Passata di pomodoro",
  tomatoes: "Pomodori",
  tortillas: "Piadine",
  tuna_can: "Tonno in scatola",
  vinegar: "Aceto",
  walnuts: "Noci",
  watermelon: "Anguria",
  white_bread: "Pane",
  white_fish: "Filetto di merluzzo",
  whole_chicken: "Pollo intero",
  wholegrain_bread: "Pane integrale",
  yogurt: "Yogurt",
  zucchini: "Zucchine",
};

/** Nome inglese normalizzato → nome italiano, per chi ha solo l'etichetta. */
const LABEL_BY_EN: Record<string, string> = {
  "almonds": "Mandorle",
  "apples": "Mele",
  "asparagus": "Asparagi",
  "avocado": "Avocado",
  "bacon": "Pancetta",
  "balsamic vinegar": "Aceto balsamico",
  "bananas": "Banane",
  "basmati rice": "Riso basmati",
  "beef mince": "Macinato di manzo",
  "bell peppers": "Peperoni",
  "black beans": "Fagioli neri",
  "black pepper": "Pepe nero",
  "blueberries": "Mirtilli",
  "broccoli": "Broccoli",
  "bulgur wheat": "Bulgur",
  "butter": "Burro",
  "cabbage": "Cavolo",
  "canned tomatoes": "Pomodori pelati",
  "canned tuna": "Tonno in scatola",
  "capers": "Capperi",
  "carrots": "Carote",
  "cauliflower": "Cavolfiore",
  "celery": "Sedano",
  "cheddar cheese": "Formaggio",
  "cherry tomatoes": "Pomodorini",
  "chicken breast": "Petto di pollo",
  "chicken thighs": "Cosce di pollo",
  "chickpeas": "Ceci",
  "cinnamon": "Cannella",
  "coffee": "Caffè",
  "cooking cream": "Panna da cucina",
  "couscous": "Couscous",
  "cucumber": "Cetrioli",
  "dried herbs": "Erbe secche",
  "eggplant": "Melanzane",
  "eggs": "Uova",
  "extra virgin olive oil": "Olio extravergine di oliva",
  "flour": "Farina",
  "free range chicken": "Pollo ruspante",
  "fresh herbs": "Erbe aromatiche",
  "garlic": "Aglio",
  "grapes": "Uva",
  "greek yogurt": "Yogurt greco",
  "green beans": "Fagiolini",
  "honey": "Miele",
  "jam": "Marmellata",
  "kale": "Cavolo nero",
  "ketchup": "Ketchup",
  "kidney beans": "Fagioli rossi",
  "leek": "Porri",
  "lemons": "Limoni",
  "mayonnaise": "Maionese",
  "melon": "Melone",
  "milk": "Latte",
  "mixed nuts": "Frutta secca",
  "mixed salad greens": "Insalata mista",
  "mixed seeds": "Semi misti",
  "mixed spices": "Spezie",
  "mozzarella": "Mozzarella",
  "mushrooms": "Funghi",
  "mustard": "Senape",
  "natural yogurt": "Yogurt",
  "oats": "Fiocchi d'avena",
  "olives": "Olive",
  "onions": "Cipolle",
  "oranges": "Arance",
  "paprika": "Paprika",
  "parmesan": "Parmigiano",
  "pasta": "Pasta",
  "peaches": "Pesche",
  "peanut butter": "Burro di arachidi",
  "pears": "Pere",
  "peas": "Piselli",
  "pita bread": "Pane pita",
  "pizza flour": "Farina per pizza",
  "pork loin": "Lonza di maiale",
  "potatoes": "Patate",
  "prawns": "Gamberetti",
  "quinoa": "Quinoa",
  "raspberries": "Lamponi",
  "red lentils": "Lenticchie rosse",
  "rice": "Riso",
  "ricotta": "Ricotta",
  "rocket": "Rucola",
  "salmon fillets": "Filetto di salmone",
  "salt": "Sale",
  "sausages": "Salsicce",
  "seasonal veg pack": "Verdure di stagione",
  "sliced ham": "Prosciutto cotto",
  "soy sauce": "Salsa di soia",
  "spinach": "Spinaci",
  "stock cubes": "Dado",
  "strawberries": "Fragole",
  "sugar": "Zucchero",
  "sunflower oil": "Olio di semi",
  "sweet potatoes": "Patate dolci",
  "sweetcorn": "Mais",
  "tahini": "Tahina",
  "tea bags": "Tè",
  "tofu": "Tofu",
  "tomato sauce": "Passata di pomodoro",
  "tomatoes": "Pomodori",
  "tortillas": "Piadine",
  "vinegar": "Aceto",
  "walnuts": "Noci",
  "watermelon": "Anguria",
  "white bread": "Pane",
  "white fish fillets": "Filetto di merluzzo",
  "whole chicken": "Pollo intero",
  "wholegrain bread": "Pane integrale",
  "zucchini": "Zucchine",
};

function norm(s: string): string {
  return s
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9 ]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Nome italiano di un prodotto, o `null` se non lo conosciamo.
 *
 * Si prova prima la chiave del catalogo, poi l'etichetta inglese. Un nome
 * già in italiano non viene toccato: `resolveIngredientKey` lo riconosce e
 * restituisce la sua stessa etichetta.
 */
export function italianLabel(nameOrKey: string): string | null {
  if (!nameOrKey) return null;
  return LABEL_BY_KEY[nameOrKey] ?? LABEL_BY_EN[norm(nameOrKey)] ?? null;
}

/** Reparti del catalogo, in italiano. */
const CATEGORY_IT: Record<string, string> = {
  Proteins: "Proteine",
  Vegetables: "Frutta e verdura",
  Fruit: "Frutta",
  Dairy: "Latticini",
  Carbohydrates: "Pane e cereali",
  "Healthy Fats": "Condimenti",
  Pantry: "Dispensa",
  Snacks: "Snack",
  Drinks: "Bevande",
  Other: "Altro",
};

export function italianCategory(category: string): string {
  return CATEGORY_IT[category] ?? category;
}
