/**
 * PDF Export — builds a multi-page summary using jsPDF.
 *
 * Includes: budget summary, meal plan, grocery list, savings.
 * Uses the user's currency. Strings come from a small per-language table
 * so the PDF matches the active app language without depending on React.
 */

import { jsPDF } from "jspdf";
import type { Plan } from "@/lib/models/plan-schema";
import type { UserProfile } from "@/lib/models";
import type { Language } from "@/lib/i18n/translations";
import type { SupermarketBasket } from "@/lib/price-data/supermarkets";
import { formatMoney } from "@/lib/country";

interface PdfStrings {
  title: string;
  budgetSummary: string;
  budget: string;
  spend: string;
  savings: string;
  zeroSpend: string;
  mealPlan: string;
  breakfast: string;
  lunch: string;
  dinner: string;
  grocery: string;
  supermarkets: string;
  cheapest: string;
  generated: string;
  yes: string;
  no: string;
}

const STRINGS: Record<Language, PdfStrings> = {
  en: { title: "Spesa Smart Plan", budgetSummary: "Budget Summary", budget: "Budget", spend: "Estimated spend", savings: "Expected savings", zeroSpend: "Zero Spend Day", mealPlan: "Weekly Meal Plan", breakfast: "Breakfast", lunch: "Lunch", dinner: "Dinner", grocery: "Grocery List", supermarkets: "Supermarket Comparison", cheapest: "Cheapest", generated: "Generated by Spesa Smart", yes: "Yes", no: "No" },
  it: { title: "Piano Spesa Smart", budgetSummary: "Riepilogo Budget", budget: "Budget", spend: "Spesa stimata", savings: "Risparmio previsto", zeroSpend: "Giorno a Zero Spese", mealPlan: "Piano Pasti Settimanale", breakfast: "Colazione", lunch: "Pranzo", dinner: "Cena", grocery: "Lista della Spesa", supermarkets: "Confronto Supermercati", cheapest: "Più economico", generated: "Generato da Spesa Smart", yes: "Sì", no: "No" },
  fr: { title: "Plan Spesa Smart", budgetSummary: "Résumé du Budget", budget: "Budget", spend: "Dépense estimée", savings: "Économies prévues", zeroSpend: "Jour sans dépense", mealPlan: "Plan de Repas Hebdomadaire", breakfast: "Petit-déjeuner", lunch: "Déjeuner", dinner: "Dîner", grocery: "Liste de Courses", supermarkets: "Comparaison de Supermarchés", cheapest: "Le moins cher", generated: "Généré par Spesa Smart", yes: "Oui", no: "Non" },
  es: { title: "Plan Spesa Smart", budgetSummary: "Resumen del Presupuesto", budget: "Presupuesto", spend: "Gasto estimado", savings: "Ahorro previsto", zeroSpend: "Día sin gasto", mealPlan: "Plan Semanal de Comidas", breakfast: "Desayuno", lunch: "Almuerzo", dinner: "Cena", grocery: "Lista de la Compra", supermarkets: "Comparación de Supermercados", cheapest: "Más barato", generated: "Generado por Spesa Smart", yes: "Sí", no: "No" },
  de: { title: "Spesa-Smart-Plan", budgetSummary: "Budget-Übersicht", budget: "Budget", spend: "Geschätzte Ausgaben", savings: "Erwartete Ersparnis", zeroSpend: "Null-Ausgaben-Tag", mealPlan: "Wochen-Essensplan", breakfast: "Frühstück", lunch: "Mittagessen", dinner: "Abendessen", grocery: "Einkaufsliste", supermarkets: "Supermarktvergleich", cheapest: "Am günstigsten", generated: "Erstellt von Spesa Smart", yes: "Ja", no: "Nein" },
};

export interface ExportPdfInput {
  plan: Plan;
  profile: UserProfile;
  language: Language;
  estimatedSpend: number;
  savings: number;
  supermarkets?: SupermarketBasket[];
}

export function exportPlanToPdf(input: ExportPdfInput): void {
  const { plan, profile, language, estimatedSpend, savings, supermarkets } = input;
  const s = STRINGS[language] ?? STRINGS.en;
  const fmt = (n: number) => formatMoney(n, profile.currency, language);
  const budget = Number(profile.budget) || 0;

  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 40;
  let y = margin;

  const ensureSpace = (needed: number) => {
    if (y + needed > pageH - margin) {
      doc.addPage();
      y = margin;
    }
  };

  // Header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(16, 185, 129);
  doc.text(s.title, margin, y);
  y += 24;
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.setFont("helvetica", "normal");
  doc.text(`${profile.city || ""}${profile.city ? " · " : ""}${profile.country || ""} · ${new Date().toLocaleDateString()}`, margin, y);
  y += 24;

  // Budget summary
  doc.setTextColor(20);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(s.budgetSummary, margin, y);
  y += 18;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  const rows: Array<[string, string]> = [
    [s.budget, fmt(budget)],
    [s.spend, fmt(estimatedSpend)],
    [s.savings, fmt(Math.max(0, savings))],
    [s.zeroSpend, profile.zeroSpendDay ? s.yes : s.no],
  ];
  for (const [k, v] of rows) {
    doc.text(k, margin, y);
    doc.text(v, pageW - margin, y, { align: "right" });
    y += 16;
  }
  y += 8;

  // Meal plan
  ensureSpace(40);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(s.mealPlan, margin, y);
  y += 18;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  for (const m of plan.mealPlan) {
    ensureSpace(48);
    doc.setFont("helvetica", "bold");
    doc.text(m.day, margin, y);
    y += 14;
    doc.setFont("helvetica", "normal");
    const lines: Array<[string, string]> = [
      [s.breakfast, m.breakfast],
      [s.lunch, m.lunch],
      [s.dinner, m.dinner],
    ];
    for (const [label, value] of lines) {
      const text = `${label}: ${value}`;
      const wrapped = doc.splitTextToSize(text, pageW - margin * 2);
      ensureSpace(wrapped.length * 12 + 2);
      doc.text(wrapped, margin + 8, y);
      y += wrapped.length * 12;
    }
    y += 6;
  }

  // Grocery list
  doc.addPage();
  y = margin;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(s.grocery, margin, y);
  y += 18;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  for (const g of plan.groceryList) {
    ensureSpace(14);
    const line = `• ${g.name} — ${g.quantity}`;
    doc.text(line, margin, y);
    doc.text(g.category, pageW - margin, y, { align: "right" });
    y += 14;
  }

  // Supermarkets
  if (supermarkets && supermarkets.length > 0) {
    y += 12;
    ensureSpace(40);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text(s.supermarkets, margin, y);
    y += 18;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    for (const sm of supermarkets) {
      ensureSpace(14);
      const tag = sm.isCheapest ? ` · ${s.cheapest}` : "";
      doc.text(`${sm.name}${tag}`, margin, y);
      doc.text(fmt(sm.total), pageW - margin, y, { align: "right" });
      y += 14;
    }
  }

  // Footer
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(140);
    doc.text(`${s.generated} — ${i}/${pages}`, pageW / 2, pageH - 16, { align: "center" });
  }

  const fname = `spesa-smart-${(profile.city || "plan").toLowerCase().replace(/[^a-z0-9]+/g, "-")}.pdf`;
  doc.save(fname);
}
