import { r, type LocalRecipe } from "./types";

export const FAMILY_BUDGET: LocalRecipe[] = [
  r({
    id: "fb-chili",
    title: "Bean Chilli",
    cuisine: "Family Budget", mealType: "dinner",
    prepMinutes: 10, cookMinutes: 30,
    ingredients: [
      { name: "Onion", quantity: "1" },
      { name: "Garlic", quantity: "3 cloves" },
      { name: "Mixed beans", quantity: "800 g" },
      { name: "Chopped tomatoes", quantity: "400 g" },
      { name: "Tomato paste", quantity: "30 g" },
      { name: "Ground cumin", quantity: "5 g" },
      { name: "Chilli powder", quantity: "5 g" },
      { name: "Vegetable oil", quantity: "20 ml" },
      { name: "Rice", quantity: "300 g" },
    ],
    steps: [
      "Sauté chopped onion and garlic in oil 6 minutes.",
      "Add cumin and chilli powder, toast 30 seconds.",
      "Stir in tomato paste, tomatoes and beans. Simmer 20 minutes.",
      "Meanwhile, cook the rice.",
      "Season and serve chilli over rice.",
    ],
    nutrition: { calories: 520, protein: 22, carbs: 92, fat: 6 },
  }),
  r({
    id: "fb-pasta-bake",
    title: "Family Pasta Bake",
    cuisine: "Family Budget", mealType: "dinner",
    prepMinutes: 10, cookMinutes: 30,
    ingredients: [
      { name: "Penne pasta", quantity: "500 g" },
      { name: "Passata", quantity: "700 g" },
      { name: "Onion", quantity: "1" },
      { name: "Garlic", quantity: "2 cloves" },
      { name: "Frozen mixed vegetables", quantity: "300 g" },
      { name: "Grated cheese", quantity: "200 g" },
      { name: "Olive oil", quantity: "20 ml" },
      { name: "Dried oregano", quantity: "5 g" },
    ],
    steps: [
      "Boil pasta 2 minutes under package time. Drain.",
      "Sauté onion and garlic in olive oil 5 minutes. Add passata and oregano; simmer 5 minutes.",
      "Stir pasta, sauce and frozen veg in a baking dish.",
      "Top with cheese and bake at 200°C for 15 minutes until golden.",
    ],
    nutrition: { calories: 620, protein: 24, carbs: 90, fat: 16 },
    allergens: ["Gluten", "Milk"],
  }),
  r({
    id: "fb-lentil-soup",
    title: "Hearty Lentil Soup",
    cuisine: "Family Budget", mealType: "lunch",
    prepMinutes: 10, cookMinutes: 35,
    ingredients: [
      { name: "Red lentils", quantity: "300 g" },
      { name: "Onion", quantity: "1" },
      { name: "Carrots", quantity: "2" },
      { name: "Celery", quantity: "2 stalks" },
      { name: "Garlic", quantity: "2 cloves" },
      { name: "Chopped tomatoes", quantity: "400 g" },
      { name: "Vegetable broth", quantity: "1.2 l" },
      { name: "Cumin", quantity: "5 g" },
      { name: "Olive oil", quantity: "20 ml" },
    ],
    steps: [
      "Sauté diced onion, carrot, celery and garlic in olive oil 8 minutes.",
      "Add cumin, lentils, tomatoes and broth. Bring to a boil.",
      "Simmer 25 minutes until lentils are very soft.",
      "Blend partially with a stick blender. Season and serve.",
    ],
    nutrition: { calories: 320, protein: 18, carbs: 50, fat: 6 },
  }),
  r({
    id: "fb-egg-fried-rice",
    title: "Egg Fried Rice",
    cuisine: "Family Budget", mealType: "dinner",
    prepMinutes: 5, cookMinutes: 10,
    ingredients: [
      { name: "Cooked rice", quantity: "600 g" },
      { name: "Eggs", quantity: "4" },
      { name: "Frozen peas", quantity: "200 g" },
      { name: "Spring onion", quantity: "3" },
      { name: "Soy sauce", quantity: "40 ml" },
      { name: "Sesame oil", quantity: "10 ml" },
      { name: "Vegetable oil", quantity: "20 ml" },
    ],
    steps: [
      "Heat vegetable oil in a wok. Scramble beaten eggs, set aside.",
      "Add rice and peas, stir-fry 4 minutes breaking up clumps.",
      "Return eggs, add soy sauce and sesame oil. Toss.",
      "Top with sliced spring onion.",
    ],
    nutrition: { calories: 480, protein: 16, carbs: 78, fat: 10 },
    allergens: ["Egg", "Soy"],
  }),
  r({
    id: "fb-shepherds",
    title: "Lentil Shepherd's Pie",
    cuisine: "Family Budget", mealType: "dinner",
    prepMinutes: 15, cookMinutes: 45,
    ingredients: [
      { name: "Potatoes", quantity: "1 kg" },
      { name: "Butter", quantity: "40 g" },
      { name: "Milk", quantity: "100 ml" },
      { name: "Brown lentils", quantity: "300 g" },
      { name: "Onion", quantity: "1" },
      { name: "Carrots", quantity: "2" },
      { name: "Tomato paste", quantity: "40 g" },
      { name: "Vegetable broth", quantity: "500 ml" },
      { name: "Worcestershire sauce", quantity: "20 ml" },
    ],
    steps: [
      "Boil potatoes 20 minutes; drain and mash with butter and milk.",
      "Sauté onion and carrot 6 minutes. Add lentils, tomato paste, broth and Worcestershire.",
      "Simmer 20 minutes until thickened.",
      "Spread lentils in a dish, top with mash, fluff with a fork.",
      "Bake at 200°C for 20 minutes until golden.",
    ],
    nutrition: { calories: 520, protein: 20, carbs: 88, fat: 10 },
    allergens: ["Milk"],
  }),
  r({
    id: "fb-veggie-curry",
    title: "Chickpea Curry",
    cuisine: "Family Budget", mealType: "dinner",
    prepMinutes: 10, cookMinutes: 25,
    ingredients: [
      { name: "Chickpeas", quantity: "800 g" },
      { name: "Onion", quantity: "1" },
      { name: "Garlic", quantity: "3 cloves" },
      { name: "Ginger", quantity: "20 g" },
      { name: "Chopped tomatoes", quantity: "400 g" },
      { name: "Coconut milk", quantity: "400 ml" },
      { name: "Curry powder", quantity: "15 g" },
      { name: "Rice", quantity: "300 g" },
      { name: "Vegetable oil", quantity: "20 ml" },
    ],
    steps: [
      "Sauté onion in oil 6 minutes. Add garlic, ginger and curry powder; toast 1 minute.",
      "Add tomatoes and coconut milk; simmer 10 minutes.",
      "Add chickpeas; simmer 10 more minutes.",
      "Serve over cooked rice.",
    ],
    nutrition: { calories: 600, protein: 18, carbs: 88, fat: 18 },
  }),
  r({
    id: "fb-oatmeal",
    title: "Banana Oatmeal",
    cuisine: "Family Budget", mealType: "breakfast",
    prepMinutes: 2, cookMinutes: 8,
    ingredients: [
      { name: "Rolled oats", quantity: "240 g" },
      { name: "Milk or water", quantity: "800 ml" },
      { name: "Bananas", quantity: "2" },
      { name: "Honey", quantity: "30 g" },
      { name: "Cinnamon", quantity: "to taste" },
    ],
    steps: [
      "Bring milk to a simmer. Add oats and cook 5 minutes, stirring.",
      "Divide between bowls. Top with sliced bananas, honey and cinnamon.",
    ],
    nutrition: { calories: 380, protein: 12, carbs: 70, fat: 6 },
    allergens: ["Milk"],
    aliases: ["oatmeal", "porridge"],
  }),
  r({
    id: "fb-toast",
    title: "Scrambled Eggs & Toast",
    cuisine: "Family Budget", mealType: "breakfast",
    prepMinutes: 5, cookMinutes: 5,
    ingredients: [
      { name: "Eggs", quantity: "8" },
      { name: "Butter", quantity: "20 g" },
      { name: "Bread", quantity: "8 slices" },
      { name: "Milk", quantity: "60 ml" },
      { name: "Salt", quantity: "to taste" },
    ],
    steps: [
      "Whisk eggs with milk and salt.",
      "Melt butter in a non-stick pan over low heat. Add eggs.",
      "Stir gently 3 minutes until just set.",
      "Toast bread and serve with the eggs.",
    ],
    nutrition: { calories: 360, protein: 22, carbs: 28, fat: 16 },
    allergens: ["Egg", "Gluten", "Milk"],
    aliases: ["scrambled eggs"],
  }),
  r({
    id: "fb-bean-wrap",
    title: "Bean & Cheese Wrap",
    cuisine: "Family Budget", mealType: "lunch",
    prepMinutes: 10, cookMinutes: 5,
    ingredients: [
      { name: "Tortillas", quantity: "8" },
      { name: "Refried beans", quantity: "500 g" },
      { name: "Grated cheese", quantity: "200 g" },
      { name: "Salsa", quantity: "200 g" },
      { name: "Lettuce", quantity: "1 head" },
    ],
    steps: [
      "Warm tortillas in a dry pan 30 seconds each side.",
      "Spread beans down the centre of each, top with cheese, salsa and shredded lettuce.",
      "Roll up tight and serve.",
    ],
    nutrition: { calories: 480, protein: 20, carbs: 64, fat: 16 },
    allergens: ["Gluten", "Milk"],
  }),
  r({
    id: "fb-tomato-pasta",
    title: "Tomato Pasta with Tuna",
    cuisine: "Family Budget", mealType: "dinner",
    prepMinutes: 5, cookMinutes: 15,
    ingredients: [
      { name: "Pasta", quantity: "500 g" },
      { name: "Canned tuna", quantity: "3 tins" },
      { name: "Passata", quantity: "500 g" },
      { name: "Garlic", quantity: "2 cloves" },
      { name: "Olive oil", quantity: "30 ml" },
      { name: "Capers", quantity: "20 g" },
      { name: "Black olives", quantity: "60 g" },
    ],
    steps: [
      "Cook pasta in salted water.",
      "Sauté sliced garlic in olive oil 1 minute. Add passata, capers, olives.",
      "Simmer 8 minutes. Flake in drained tuna; warm through.",
      "Toss with drained pasta and serve.",
    ],
    nutrition: { calories: 540, protein: 28, carbs: 78, fat: 12 },
    allergens: ["Gluten", "Fish/Shellfish"],
  }),
];
