import { r, type LocalRecipe } from "./types";

export const ITALIAN: LocalRecipe[] = [
  r({
    id: "it-margherita",
    title: "Pizza Margherita",
    cuisine: "Italian", mealType: "dinner",
    prepMinutes: 90, cookMinutes: 10, difficulty: "medium",
    ingredients: [
      { name: "00 flour", quantity: "500 g" },
      { name: "Water", quantity: "325 ml" },
      { name: "Fresh yeast", quantity: "3 g" },
      { name: "Salt", quantity: "10 g" },
      { name: "Tomato passata", quantity: "300 g" },
      { name: "Fresh mozzarella", quantity: "300 g" },
      { name: "Fresh basil", quantity: "12 leaves" },
      { name: "Extra virgin olive oil", quantity: "30 ml" },
    ],
    steps: [
      "Dissolve yeast in water, mix in flour, then salt. Knead 10 minutes until smooth.",
      "Cover and rise at room temperature for 1 hour, then divide into 4 balls and rest 30 minutes.",
      "Heat oven to its maximum (250°C+) with a pizza stone or steel inside for 30 minutes.",
      "Stretch each ball into a 28 cm round. Spread 75 g passata, season with salt.",
      "Tear mozzarella over the top and drizzle with olive oil.",
      "Bake 6–8 minutes until the crust is blistered and the cheese bubbling.",
      "Top with fresh basil leaves before serving.",
    ],
    nutrition: { calories: 620, protein: 24, carbs: 78, fat: 22 },
    allergens: ["Gluten", "Milk"],
    aliases: ["margherita", "pizza", "homemade pizza"],
  }),
  r({
    id: "it-pomodoro",
    title: "Pasta Pomodoro",
    cuisine: "Italian", mealType: "dinner",
    prepMinutes: 5, cookMinutes: 20,
    ingredients: [
      { name: "Spaghetti", quantity: "400 g" },
      { name: "San Marzano tomatoes", quantity: "800 g" },
      { name: "Garlic", quantity: "3 cloves" },
      { name: "Fresh basil", quantity: "10 leaves" },
      { name: "Extra virgin olive oil", quantity: "40 ml" },
      { name: "Salt", quantity: "to taste" },
      { name: "Parmesan", quantity: "40 g" },
    ],
    steps: [
      "Bring a large pot of salted water to a boil.",
      "In a wide pan, warm olive oil and gently sizzle smashed garlic 1 minute.",
      "Add tomatoes, crush with a spoon, season with salt, simmer 12 minutes.",
      "Cook spaghetti 1 minute under package time, reserving 200 ml pasta water.",
      "Toss pasta with sauce and a splash of pasta water until creamy.",
      "Finish with torn basil and grated parmesan.",
    ],
    nutrition: { calories: 520, protein: 18, carbs: 82, fat: 14 },
    allergens: ["Gluten", "Milk"],
    aliases: ["spaghetti", "tomato pasta", "pasta"],
  }),
  r({
    id: "it-carbonara",
    title: "Spaghetti alla Carbonara",
    cuisine: "Italian", mealType: "dinner",
    prepMinutes: 5, cookMinutes: 15, difficulty: "medium",
    ingredients: [
      { name: "Spaghetti", quantity: "400 g" },
      { name: "Guanciale", quantity: "200 g" },
      { name: "Egg yolks", quantity: "4" },
      { name: "Whole egg", quantity: "1" },
      { name: "Pecorino Romano", quantity: "80 g" },
      { name: "Black pepper", quantity: "to taste" },
      { name: "Salt", quantity: "to taste" },
    ],
    steps: [
      "Cook spaghetti in salted water until al dente.",
      "Render guanciale in a dry pan until crisp; remove from heat.",
      "Whisk yolks, whole egg, pecorino and lots of pepper in a bowl.",
      "Drain pasta, reserving 150 ml cooking water. Toss pasta in the guanciale pan.",
      "Off the heat, add the egg mixture and a splash of pasta water; toss vigorously to a silky sauce.",
      "Serve immediately with more pecorino and pepper.",
    ],
    nutrition: { calories: 720, protein: 32, carbs: 70, fat: 32 },
    allergens: ["Gluten", "Milk", "Egg"],
  }),
  r({
    id: "it-minestrone",
    title: "Minestrone Soup",
    cuisine: "Italian", mealType: "lunch",
    prepMinutes: 15, cookMinutes: 40,
    ingredients: [
      { name: "Onion", quantity: "1" },
      { name: "Carrots", quantity: "2" },
      { name: "Celery", quantity: "2 stalks" },
      { name: "Zucchini", quantity: "1" },
      { name: "Cannellini beans", quantity: "400 g" },
      { name: "Crushed tomatoes", quantity: "400 g" },
      { name: "Vegetable broth", quantity: "1 l" },
      { name: "Ditalini pasta", quantity: "150 g" },
      { name: "Olive oil", quantity: "30 ml" },
      { name: "Parmesan rind", quantity: "1 piece" },
    ],
    steps: [
      "Dice onion, carrot, celery, zucchini. Sauté in olive oil 8 minutes.",
      "Add tomatoes, broth and parmesan rind. Simmer 20 minutes.",
      "Add beans and pasta, cook 10 more minutes until pasta is tender.",
      "Season, remove rind, drizzle with olive oil and serve.",
    ],
    nutrition: { calories: 380, protein: 16, carbs: 58, fat: 10 },
    allergens: ["Gluten", "Milk"],
  }),
  r({
    id: "it-risotto",
    title: "Mushroom Risotto",
    cuisine: "Italian", mealType: "dinner",
    prepMinutes: 10, cookMinutes: 30, difficulty: "medium",
    ingredients: [
      { name: "Arborio rice", quantity: "320 g" },
      { name: "Mixed mushrooms", quantity: "400 g" },
      { name: "Shallot", quantity: "1" },
      { name: "Dry white wine", quantity: "120 ml" },
      { name: "Vegetable broth", quantity: "1 l" },
      { name: "Butter", quantity: "60 g" },
      { name: "Parmesan", quantity: "60 g" },
      { name: "Olive oil", quantity: "20 ml" },
    ],
    steps: [
      "Sauté sliced mushrooms in olive oil until browned. Set aside.",
      "In same pan, soften minced shallot in butter. Add rice and toast 2 minutes.",
      "Pour in wine, stir until absorbed.",
      "Add hot broth a ladle at a time, stirring, until rice is creamy and al dente (18 min).",
      "Off the heat, stir in mushrooms, remaining butter and parmesan. Rest 2 minutes and serve.",
    ],
    nutrition: { calories: 560, protein: 16, carbs: 78, fat: 18 },
    allergens: ["Milk"],
  }),
  r({
    id: "it-frittata",
    title: "Zucchini Frittata",
    cuisine: "Italian", mealType: "breakfast",
    prepMinutes: 10, cookMinutes: 15,
    ingredients: [
      { name: "Eggs", quantity: "8" },
      { name: "Zucchini", quantity: "2" },
      { name: "Parmesan", quantity: "50 g" },
      { name: "Olive oil", quantity: "20 ml" },
      { name: "Salt", quantity: "to taste" },
      { name: "Black pepper", quantity: "to taste" },
    ],
    steps: [
      "Slice zucchini and sauté in olive oil 6 minutes until soft.",
      "Whisk eggs with parmesan, salt and pepper.",
      "Pour egg mixture over zucchini. Cook on low 6 minutes until set on the bottom.",
      "Finish under the grill 2 minutes until puffed and golden.",
    ],
    nutrition: { calories: 320, protein: 22, carbs: 6, fat: 22 },
    allergens: ["Egg", "Milk"],
  }),
  r({
    id: "it-bruschetta",
    title: "Tomato Bruschetta",
    cuisine: "Italian", mealType: "lunch",
    prepMinutes: 10, cookMinutes: 5,
    ingredients: [
      { name: "Sourdough bread", quantity: "8 slices" },
      { name: "Ripe tomatoes", quantity: "500 g" },
      { name: "Garlic", quantity: "2 cloves" },
      { name: "Fresh basil", quantity: "10 leaves" },
      { name: "Extra virgin olive oil", quantity: "40 ml" },
      { name: "Salt", quantity: "to taste" },
    ],
    steps: [
      "Toast or grill bread slices until golden.",
      "Rub each slice with a halved garlic clove while warm.",
      "Dice tomatoes, season with salt, olive oil and torn basil.",
      "Spoon topping over the bread and serve immediately.",
    ],
    nutrition: { calories: 340, protein: 9, carbs: 50, fat: 12 },
    allergens: ["Gluten"],
  }),
  r({
    id: "it-cacciatore",
    title: "Chicken Cacciatore",
    cuisine: "Italian", mealType: "dinner",
    prepMinutes: 15, cookMinutes: 45,
    ingredients: [
      { name: "Chicken thighs", quantity: "1 kg" },
      { name: "Onion", quantity: "1" },
      { name: "Bell peppers", quantity: "2" },
      { name: "Crushed tomatoes", quantity: "400 g" },
      { name: "Black olives", quantity: "100 g" },
      { name: "Dry white wine", quantity: "150 ml" },
      { name: "Olive oil", quantity: "30 ml" },
      { name: "Rosemary", quantity: "2 sprigs" },
    ],
    steps: [
      "Season chicken with salt and pepper. Brown in olive oil, set aside.",
      "Sauté sliced onion and peppers in the same pan 8 minutes.",
      "Deglaze with wine, add tomatoes, olives and rosemary.",
      "Return chicken, cover and simmer 30 minutes until tender.",
      "Serve with crusty bread or polenta.",
    ],
    nutrition: { calories: 540, protein: 42, carbs: 14, fat: 30 },
  }),
  r({
    id: "it-caprese",
    title: "Caprese Salad",
    cuisine: "Italian", mealType: "lunch",
    prepMinutes: 10, cookMinutes: 0,
    ingredients: [
      { name: "Fresh mozzarella", quantity: "400 g" },
      { name: "Ripe tomatoes", quantity: "500 g" },
      { name: "Fresh basil", quantity: "20 leaves" },
      { name: "Extra virgin olive oil", quantity: "40 ml" },
      { name: "Salt", quantity: "to taste" },
    ],
    steps: [
      "Slice mozzarella and tomatoes into 1 cm rounds.",
      "Alternate slices on a platter, tucking basil leaves between.",
      "Season with flaky salt and drizzle generously with olive oil.",
    ],
    nutrition: { calories: 380, protein: 22, carbs: 8, fat: 28 },
    allergens: ["Milk"],
  }),
  r({
    id: "it-cornetto",
    title: "Italian Breakfast Cornetto & Cappuccino",
    cuisine: "Italian", mealType: "breakfast",
    prepMinutes: 5, cookMinutes: 5,
    ingredients: [
      { name: "Cornetto (croissant)", quantity: "4" },
      { name: "Espresso", quantity: "4 shots" },
      { name: "Whole milk", quantity: "400 ml" },
      { name: "Honey or jam", quantity: "60 g" },
    ],
    steps: [
      "Warm cornetti 3 minutes in a 180°C oven.",
      "Brew espresso for each cup.",
      "Steam milk to silky microfoam and pour over espresso.",
      "Serve with honey or jam alongside.",
    ],
    nutrition: { calories: 420, protein: 11, carbs: 50, fat: 18 },
    allergens: ["Gluten", "Milk"],
  }),
];
