import { r, type LocalRecipe } from "./types";

export const JAPANESE: LocalRecipe[] = [
  r({
    id: "jp-teriyaki",
    title: "Chicken Teriyaki",
    cuisine: "Japanese", mealType: "dinner",
    prepMinutes: 10, cookMinutes: 15,
    ingredients: [
      { name: "Boneless chicken thighs", quantity: "600 g" },
      { name: "Soy sauce", quantity: "60 ml" },
      { name: "Mirin", quantity: "60 ml" },
      { name: "Sake", quantity: "30 ml" },
      { name: "Sugar", quantity: "20 g" },
      { name: "Steamed rice", quantity: "600 g" },
      { name: "Spring onion", quantity: "2" },
      { name: "Sesame seeds", quantity: "10 g" },
    ],
    steps: [
      "Mix soy, mirin, sake and sugar in a small bowl.",
      "Sear chicken thighs skin-side down in a hot pan 6 minutes until crisp.",
      "Flip and cook 4 more minutes. Drain excess fat.",
      "Pour in sauce; simmer 3 minutes until glossy and coating the chicken.",
      "Slice and serve over rice, topped with spring onion and sesame seeds.",
    ],
    nutrition: { calories: 620, protein: 38, carbs: 70, fat: 18 },
    allergens: ["Soy"],
    aliases: ["teriyaki"],
  }),
  r({
    id: "jp-miso-soup",
    title: "Miso Soup",
    cuisine: "Japanese", mealType: "breakfast",
    prepMinutes: 5, cookMinutes: 10,
    ingredients: [
      { name: "Dashi stock", quantity: "1 l" },
      { name: "Miso paste", quantity: "60 g" },
      { name: "Silken tofu", quantity: "200 g" },
      { name: "Wakame seaweed", quantity: "10 g" },
      { name: "Spring onion", quantity: "2" },
    ],
    steps: [
      "Bring dashi to a gentle simmer; add cubed tofu and rehydrated wakame.",
      "Whisk miso with a ladle of warm dashi until smooth.",
      "Off the heat, stir miso into the pot. Do not boil.",
      "Top with sliced spring onion and serve.",
    ],
    nutrition: { calories: 110, protein: 9, carbs: 8, fat: 4 },
    allergens: ["Soy"],
  }),
  r({
    id: "jp-sushi-bowl",
    title: "Salmon Sushi Bowl",
    cuisine: "Japanese", mealType: "lunch",
    prepMinutes: 15, cookMinutes: 20,
    ingredients: [
      { name: "Sushi rice", quantity: "400 g" },
      { name: "Rice vinegar", quantity: "60 ml" },
      { name: "Sugar", quantity: "20 g" },
      { name: "Salt", quantity: "5 g" },
      { name: "Sashimi-grade salmon", quantity: "500 g" },
      { name: "Avocado", quantity: "1" },
      { name: "Cucumber", quantity: "1" },
      { name: "Nori sheets", quantity: "2" },
      { name: "Soy sauce", quantity: "to serve" },
    ],
    steps: [
      "Rinse and cook sushi rice. Warm vinegar with sugar and salt; fold into rice.",
      "Slice salmon, avocado and cucumber.",
      "Divide rice into bowls. Top with salmon, avocado, cucumber and shredded nori.",
      "Serve with soy sauce.",
    ],
    nutrition: { calories: 680, protein: 32, carbs: 80, fat: 22 },
    allergens: ["Fish/Shellfish", "Soy"],
    aliases: ["poke", "sushi"],
  }),
  r({
    id: "jp-yakisoba",
    title: "Yakisoba Noodles",
    cuisine: "Japanese", mealType: "dinner",
    prepMinutes: 10, cookMinutes: 12,
    ingredients: [
      { name: "Yakisoba noodles", quantity: "500 g" },
      { name: "Pork or chicken", quantity: "300 g" },
      { name: "Cabbage", quantity: "300 g" },
      { name: "Carrot", quantity: "1" },
      { name: "Bell pepper", quantity: "1" },
      { name: "Yakisoba sauce", quantity: "80 ml" },
      { name: "Sesame oil", quantity: "20 ml" },
      { name: "Pickled ginger", quantity: "30 g" },
    ],
    steps: [
      "Heat sesame oil in a wok; stir-fry sliced meat until just cooked.",
      "Add shredded cabbage, sliced carrot and pepper; stir-fry 3 minutes.",
      "Add noodles with a splash of water to loosen; toss.",
      "Pour in yakisoba sauce; stir-fry 2 minutes until glossy.",
      "Plate and top with pickled ginger.",
    ],
    nutrition: { calories: 580, protein: 26, carbs: 78, fat: 18 },
    allergens: ["Gluten", "Soy"],
  }),
  r({
    id: "jp-katsu-curry",
    title: "Chicken Katsu Curry",
    cuisine: "Japanese", mealType: "dinner",
    prepMinutes: 15, cookMinutes: 30, difficulty: "medium",
    ingredients: [
      { name: "Chicken breast", quantity: "600 g" },
      { name: "Panko breadcrumbs", quantity: "150 g" },
      { name: "Flour", quantity: "80 g" },
      { name: "Egg", quantity: "2" },
      { name: "Japanese curry roux", quantity: "100 g" },
      { name: "Onion", quantity: "1" },
      { name: "Carrot", quantity: "1" },
      { name: "Potato", quantity: "1" },
      { name: "Steamed rice", quantity: "600 g" },
      { name: "Frying oil", quantity: "500 ml" },
    ],
    steps: [
      "Sauté chopped onion, carrot and potato 5 minutes. Add 700 ml water; simmer 15 minutes.",
      "Off the heat, dissolve curry roux into the sauce.",
      "Flatten chicken slightly. Coat in flour, egg, then panko.",
      "Fry chicken at 170°C 4 minutes per side until golden. Rest, then slice.",
      "Serve katsu over rice with curry sauce ladled around.",
    ],
    nutrition: { calories: 780, protein: 42, carbs: 90, fat: 26 },
    allergens: ["Gluten", "Egg", "Soy"],
    aliases: ["katsu", "tonkatsu"],
  }),
  r({
    id: "jp-ramen",
    title: "Shoyu Ramen",
    cuisine: "Japanese", mealType: "dinner",
    prepMinutes: 10, cookMinutes: 25,
    ingredients: [
      { name: "Ramen noodles", quantity: "400 g" },
      { name: "Chicken stock", quantity: "1.2 l" },
      { name: "Soy sauce", quantity: "80 ml" },
      { name: "Mirin", quantity: "30 ml" },
      { name: "Sliced pork or chicken", quantity: "300 g" },
      { name: "Eggs", quantity: "4" },
      { name: "Spring onion", quantity: "2" },
      { name: "Nori sheets", quantity: "2" },
      { name: "Garlic", quantity: "2 cloves" },
      { name: "Ginger", quantity: "20 g" },
    ],
    steps: [
      "Soft-boil eggs 7 minutes, cool and peel.",
      "Simmer stock with crushed garlic and ginger 10 minutes. Add soy and mirin.",
      "Sear pork or chicken slices and set aside.",
      "Cook noodles per package. Divide between 4 bowls.",
      "Ladle hot broth over noodles. Top with meat, halved egg, spring onion and nori.",
    ],
    nutrition: { calories: 640, protein: 32, carbs: 78, fat: 22 },
    allergens: ["Gluten", "Soy", "Egg"],
    aliases: ["ramen"],
  }),
  r({
    id: "jp-tamagoyaki",
    title: "Tamagoyaki (Rolled Omelette)",
    cuisine: "Japanese", mealType: "breakfast",
    prepMinutes: 5, cookMinutes: 10,
    ingredients: [
      { name: "Eggs", quantity: "6" },
      { name: "Soy sauce", quantity: "10 ml" },
      { name: "Mirin", quantity: "15 ml" },
      { name: "Sugar", quantity: "10 g" },
      { name: "Neutral oil", quantity: "10 ml" },
    ],
    steps: [
      "Beat eggs with soy, mirin and sugar.",
      "Lightly oil a small non-stick pan over medium heat.",
      "Pour a thin layer of egg, let set, roll to one side of the pan.",
      "Pour another thin layer, lift the roll so egg flows under, then roll over the new layer.",
      "Repeat until egg is used. Slice into 2 cm pieces and serve.",
    ],
    nutrition: { calories: 220, protein: 16, carbs: 4, fat: 14 },
    allergens: ["Egg", "Soy"],
  }),
  r({
    id: "jp-miso-cod",
    title: "Miso Glazed Cod",
    cuisine: "Japanese", mealType: "dinner",
    prepMinutes: 10, cookMinutes: 12,
    ingredients: [
      { name: "Cod fillets", quantity: "600 g" },
      { name: "White miso", quantity: "60 g" },
      { name: "Mirin", quantity: "40 ml" },
      { name: "Sake", quantity: "30 ml" },
      { name: "Sugar", quantity: "20 g" },
      { name: "Steamed rice", quantity: "500 g" },
      { name: "Bok choy", quantity: "300 g" },
    ],
    steps: [
      "Warm miso, mirin, sake and sugar in a pan until smooth. Cool.",
      "Marinate cod in the glaze 30 minutes.",
      "Grill or broil cod 4 minutes per side until caramelised.",
      "Steam bok choy. Serve cod with rice and greens.",
    ],
    nutrition: { calories: 480, protein: 36, carbs: 60, fat: 8 },
    allergens: ["Fish/Shellfish", "Soy"],
  }),
  r({
    id: "jp-onigiri",
    title: "Salmon Onigiri",
    cuisine: "Japanese", mealType: "lunch",
    prepMinutes: 15, cookMinutes: 20,
    ingredients: [
      { name: "Sushi rice", quantity: "400 g" },
      { name: "Cooked salmon", quantity: "200 g" },
      { name: "Nori sheets", quantity: "4" },
      { name: "Salt", quantity: "5 g" },
      { name: "Soy sauce", quantity: "20 ml" },
    ],
    steps: [
      "Cook sushi rice and let cool until just warm.",
      "Flake salmon and mix with soy.",
      "Wet hands with salted water. Form rice into triangles, stuffing salmon inside.",
      "Wrap with nori strips and serve.",
    ],
    nutrition: { calories: 380, protein: 18, carbs: 64, fat: 6 },
    allergens: ["Fish/Shellfish", "Soy"],
  }),
  r({
    id: "jp-gyoza",
    title: "Veggie Gyoza & Rice",
    cuisine: "Japanese", mealType: "dinner",
    prepMinutes: 20, cookMinutes: 15,
    ingredients: [
      { name: "Gyoza wrappers", quantity: "30" },
      { name: "Cabbage", quantity: "300 g" },
      { name: "Carrot", quantity: "1" },
      { name: "Spring onion", quantity: "2" },
      { name: "Ginger", quantity: "20 g" },
      { name: "Soy sauce", quantity: "30 ml" },
      { name: "Sesame oil", quantity: "20 ml" },
      { name: "Steamed rice", quantity: "500 g" },
    ],
    steps: [
      "Finely chop cabbage, carrot, spring onion, ginger. Squeeze out moisture.",
      "Mix with soy sauce and sesame oil.",
      "Place 1 tsp filling on each wrapper, wet edges and pleat shut.",
      "Pan-fry flat-side down 3 minutes until crisp. Add 80 ml water, cover, steam 5 minutes.",
      "Uncover and cook off remaining water. Serve with rice and dipping soy.",
    ],
    nutrition: { calories: 520, protein: 14, carbs: 88, fat: 10 },
    allergens: ["Gluten", "Soy"],
  }),
];
