import { r, type LocalRecipe } from "./types";

export const LOW_CARB: LocalRecipe[] = [
  r({
    id: "lc-chicken-greens",
    title: "Grilled Chicken & Greens",
    cuisine: "Low Carb", mealType: "dinner",
    prepMinutes: 10, cookMinutes: 15,
    ingredients: [
      { name: "Chicken breast", quantity: "700 g" },
      { name: "Mixed salad greens", quantity: "300 g" },
      { name: "Cherry tomatoes", quantity: "300 g" },
      { name: "Cucumber", quantity: "1" },
      { name: "Olive oil", quantity: "40 ml" },
      { name: "Lemon", quantity: "1" },
      { name: "Salt", quantity: "to taste" },
    ],
    steps: [
      "Season chicken with salt and pepper. Grill 6 minutes per side; rest 5 minutes.",
      "Toss greens, halved tomatoes, sliced cucumber with olive oil and lemon juice.",
      "Slice chicken and serve over the salad.",
    ],
    nutrition: { calories: 380, protein: 42, carbs: 8, fat: 18 },
  }),
  r({
    id: "lc-salmon",
    title: "Pan-seared Salmon with Asparagus",
    cuisine: "Low Carb", mealType: "dinner",
    prepMinutes: 5, cookMinutes: 12,
    ingredients: [
      { name: "Salmon fillets", quantity: "600 g" },
      { name: "Asparagus", quantity: "500 g" },
      { name: "Butter", quantity: "30 g" },
      { name: "Lemon", quantity: "1" },
      { name: "Garlic", quantity: "2 cloves" },
      { name: "Olive oil", quantity: "20 ml" },
    ],
    steps: [
      "Sear salmon skin-side down in olive oil 5 minutes until crisp.",
      "Flip, add butter, garlic and lemon zest. Baste 2 minutes.",
      "Roast asparagus at 220°C with oil and salt 8 minutes.",
      "Plate salmon over asparagus with pan butter spooned over.",
    ],
    nutrition: { calories: 460, protein: 38, carbs: 6, fat: 30 },
    allergens: ["Fish/Shellfish", "Milk"],
  }),
  r({
    id: "lc-zoodles",
    title: "Zoodle Bolognese",
    cuisine: "Low Carb", mealType: "dinner",
    prepMinutes: 10, cookMinutes: 30,
    ingredients: [
      { name: "Zucchini", quantity: "1 kg" },
      { name: "Ground beef", quantity: "500 g" },
      { name: "Onion", quantity: "1" },
      { name: "Garlic", quantity: "3 cloves" },
      { name: "Crushed tomatoes", quantity: "400 g" },
      { name: "Olive oil", quantity: "30 ml" },
      { name: "Parmesan", quantity: "40 g" },
    ],
    steps: [
      "Spiralize zucchini into noodles.",
      "Brown ground beef. Add diced onion and garlic; cook 5 minutes.",
      "Add tomatoes and simmer 20 minutes.",
      "Sauté zoodles in olive oil 2 minutes until just tender.",
      "Top zoodles with sauce and parmesan.",
    ],
    nutrition: { calories: 420, protein: 32, carbs: 18, fat: 24 },
    allergens: ["Milk"],
  }),
  r({
    id: "lc-omelette",
    title: "Cheese & Spinach Omelette",
    cuisine: "Low Carb", mealType: "breakfast",
    prepMinutes: 5, cookMinutes: 8,
    ingredients: [
      { name: "Eggs", quantity: "8" },
      { name: "Spinach", quantity: "200 g" },
      { name: "Cheese", quantity: "120 g" },
      { name: "Butter", quantity: "20 g" },
    ],
    steps: [
      "Wilt spinach in butter 2 minutes. Set aside.",
      "Whisk eggs with salt.",
      "Cook eggs in butter; when nearly set, add spinach and cheese to one half.",
      "Fold and slide onto a plate.",
    ],
    nutrition: { calories: 360, protein: 26, carbs: 4, fat: 26 },
    allergens: ["Egg", "Milk"],
  }),
  r({
    id: "lc-lettuce-tacos",
    title: "Beef Lettuce Tacos",
    cuisine: "Low Carb", mealType: "dinner",
    prepMinutes: 10, cookMinutes: 15,
    ingredients: [
      { name: "Ground beef", quantity: "600 g" },
      { name: "Onion", quantity: "1" },
      { name: "Garlic", quantity: "2 cloves" },
      { name: "Taco seasoning", quantity: "20 g" },
      { name: "Romaine or iceberg lettuce", quantity: "1 head" },
      { name: "Cheese", quantity: "100 g" },
      { name: "Salsa", quantity: "200 g" },
      { name: "Avocado", quantity: "1" },
    ],
    steps: [
      "Brown beef with onion and garlic.",
      "Add taco seasoning and 80 ml water; simmer 5 minutes.",
      "Separate lettuce into leaves.",
      "Spoon beef into leaves, top with cheese, salsa and sliced avocado.",
    ],
    nutrition: { calories: 460, protein: 32, carbs: 10, fat: 30 },
    allergens: ["Milk"],
  }),
  r({
    id: "lc-cauli-curry",
    title: "Cauliflower Chicken Curry",
    cuisine: "Low Carb", mealType: "dinner",
    prepMinutes: 10, cookMinutes: 25,
    ingredients: [
      { name: "Chicken thighs", quantity: "700 g" },
      { name: "Cauliflower", quantity: "1 head" },
      { name: "Onion", quantity: "1" },
      { name: "Coconut milk", quantity: "400 ml" },
      { name: "Curry powder", quantity: "15 g" },
      { name: "Ginger", quantity: "20 g" },
      { name: "Olive oil", quantity: "20 ml" },
    ],
    steps: [
      "Brown chicken in oil. Remove.",
      "Sauté onion and ginger 5 minutes. Add curry powder; toast 1 minute.",
      "Add coconut milk and cauliflower florets. Simmer 10 minutes.",
      "Return chicken; simmer 5 more minutes.",
    ],
    nutrition: { calories: 520, protein: 36, carbs: 14, fat: 34 },
  }),
  r({
    id: "lc-yogurt-bowl",
    title: "Greek Yogurt Berry Bowl",
    cuisine: "Low Carb", mealType: "breakfast",
    prepMinutes: 5, cookMinutes: 0,
    ingredients: [
      { name: "Greek yogurt", quantity: "600 g" },
      { name: "Mixed berries", quantity: "300 g" },
      { name: "Almonds", quantity: "80 g" },
      { name: "Chia seeds", quantity: "20 g" },
    ],
    steps: [
      "Divide yogurt between bowls.",
      "Top with berries, almonds and chia seeds.",
    ],
    nutrition: { calories: 320, protein: 22, carbs: 18, fat: 18 },
    allergens: ["Milk", "Nuts"],
  }),
  r({
    id: "lc-steak",
    title: "Steak & Salad",
    cuisine: "Low Carb", mealType: "dinner",
    prepMinutes: 5, cookMinutes: 10,
    ingredients: [
      { name: "Beef steak", quantity: "600 g" },
      { name: "Mixed salad greens", quantity: "300 g" },
      { name: "Cherry tomatoes", quantity: "250 g" },
      { name: "Blue cheese", quantity: "80 g" },
      { name: "Olive oil", quantity: "40 ml" },
      { name: "Balsamic vinegar", quantity: "20 ml" },
    ],
    steps: [
      "Season steak with salt and pepper. Sear 3 minutes per side; rest 5 minutes.",
      "Whisk olive oil and balsamic; toss with greens and tomatoes.",
      "Slice steak; serve over salad, topped with crumbled blue cheese.",
    ],
    nutrition: { calories: 540, protein: 42, carbs: 8, fat: 38 },
    allergens: ["Milk"],
  }),
  r({
    id: "lc-stuffed-peppers",
    title: "Stuffed Bell Peppers",
    cuisine: "Low Carb", mealType: "dinner",
    prepMinutes: 15, cookMinutes: 35,
    ingredients: [
      { name: "Bell peppers", quantity: "6" },
      { name: "Ground turkey", quantity: "500 g" },
      { name: "Cauliflower rice", quantity: "300 g" },
      { name: "Crushed tomatoes", quantity: "200 g" },
      { name: "Onion", quantity: "1" },
      { name: "Cheese", quantity: "150 g" },
      { name: "Olive oil", quantity: "20 ml" },
    ],
    steps: [
      "Halve peppers and remove seeds.",
      "Brown turkey with chopped onion. Add cauliflower rice and tomatoes; cook 5 minutes.",
      "Stuff peppers, top with cheese.",
      "Bake at 200°C for 25 minutes until peppers are tender and cheese golden.",
    ],
    nutrition: { calories: 380, protein: 30, carbs: 18, fat: 20 },
    allergens: ["Milk"],
  }),
  r({
    id: "lc-tuna-salad",
    title: "Tuna Avocado Salad",
    cuisine: "Low Carb", mealType: "lunch",
    prepMinutes: 10, cookMinutes: 0,
    ingredients: [
      { name: "Canned tuna", quantity: "4 tins" },
      { name: "Avocado", quantity: "2" },
      { name: "Red onion", quantity: "0.5" },
      { name: "Lemon", quantity: "1" },
      { name: "Mixed salad greens", quantity: "200 g" },
      { name: "Olive oil", quantity: "30 ml" },
    ],
    steps: [
      "Flake tuna into a bowl.",
      "Mash avocado with lemon juice and finely diced onion.",
      "Fold tuna into avocado.",
      "Serve over greens, drizzled with olive oil.",
    ],
    nutrition: { calories: 380, protein: 32, carbs: 10, fat: 24 },
    allergens: ["Fish/Shellfish"],
  }),
];
