import { r, type LocalRecipe } from "./types";

export const MEDITERRANEAN: LocalRecipe[] = [
  r({
    id: "med-greek-salad",
    title: "Greek Salad",
    cuisine: "Mediterranean", mealType: "lunch",
    prepMinutes: 15, cookMinutes: 0,
    ingredients: [
      { name: "Ripe tomatoes", quantity: "600 g" },
      { name: "Cucumber", quantity: "1" },
      { name: "Red onion", quantity: "1" },
      { name: "Feta cheese", quantity: "200 g" },
      { name: "Kalamata olives", quantity: "120 g" },
      { name: "Extra virgin olive oil", quantity: "60 ml" },
      { name: "Red wine vinegar", quantity: "20 ml" },
      { name: "Dried oregano", quantity: "5 g" },
    ],
    steps: [
      "Cut tomatoes into wedges and cucumber into thick slices.",
      "Thinly slice red onion.",
      "Combine vegetables with olives; top with feta in one block.",
      "Drizzle with olive oil and vinegar; sprinkle oregano.",
    ],
    nutrition: { calories: 360, protein: 12, carbs: 18, fat: 28 },
    allergens: ["Milk"],
  }),
  r({
    id: "med-shakshuka",
    title: "Shakshuka",
    cuisine: "Mediterranean", mealType: "breakfast",
    prepMinutes: 10, cookMinutes: 20,
    ingredients: [
      { name: "Eggs", quantity: "8" },
      { name: "Chopped tomatoes", quantity: "800 g" },
      { name: "Bell peppers", quantity: "2" },
      { name: "Onion", quantity: "1" },
      { name: "Garlic", quantity: "3 cloves" },
      { name: "Smoked paprika", quantity: "5 g" },
      { name: "Cumin", quantity: "5 g" },
      { name: "Olive oil", quantity: "30 ml" },
      { name: "Feta", quantity: "120 g" },
    ],
    steps: [
      "Sauté onion and peppers in olive oil 8 minutes. Add garlic and spices.",
      "Pour in tomatoes; simmer 8 minutes until thick.",
      "Make 8 wells; crack an egg into each.",
      "Cover and cook 6 minutes until whites are set.",
      "Crumble feta over the top and serve with bread.",
    ],
    nutrition: { calories: 380, protein: 22, carbs: 22, fat: 22 },
    allergens: ["Egg", "Milk"],
  }),
  r({
    id: "med-traybake",
    title: "Mediterranean Chicken Traybake",
    cuisine: "Mediterranean", mealType: "dinner",
    prepMinutes: 10, cookMinutes: 40,
    ingredients: [
      { name: "Chicken thighs", quantity: "1 kg" },
      { name: "Cherry tomatoes", quantity: "400 g" },
      { name: "Bell peppers", quantity: "2" },
      { name: "Red onion", quantity: "1" },
      { name: "Olives", quantity: "100 g" },
      { name: "Olive oil", quantity: "40 ml" },
      { name: "Lemon", quantity: "1" },
      { name: "Dried oregano", quantity: "10 g" },
      { name: "Garlic", quantity: "4 cloves" },
    ],
    steps: [
      "Heat oven to 220°C.",
      "Toss chicken with vegetables, smashed garlic, olive oil, oregano and lemon juice.",
      "Spread on a sheet pan.",
      "Roast 35 minutes until chicken is cooked through and veg caramelised.",
    ],
    nutrition: { calories: 540, protein: 38, carbs: 16, fat: 32 },
  }),
  r({
    id: "med-hummus-plate",
    title: "Hummus & Mezze Plate",
    cuisine: "Mediterranean", mealType: "lunch",
    prepMinutes: 15, cookMinutes: 0,
    ingredients: [
      { name: "Chickpeas", quantity: "500 g" },
      { name: "Tahini", quantity: "80 g" },
      { name: "Lemon", quantity: "1" },
      { name: "Garlic", quantity: "1 clove" },
      { name: "Olive oil", quantity: "60 ml" },
      { name: "Pita bread", quantity: "4" },
      { name: "Cucumber", quantity: "1" },
      { name: "Cherry tomatoes", quantity: "200 g" },
      { name: "Olives", quantity: "100 g" },
    ],
    steps: [
      "Blend chickpeas, tahini, lemon juice, garlic and 60 ml water until smooth.",
      "Spread hummus on a plate; drizzle with olive oil.",
      "Serve with warmed pita, cucumber, tomatoes and olives.",
    ],
    nutrition: { calories: 540, protein: 18, carbs: 60, fat: 26 },
    allergens: ["Gluten"],
  }),
  r({
    id: "med-salmon-trbk",
    title: "Mediterranean Salmon Traybake",
    cuisine: "Mediterranean", mealType: "dinner",
    prepMinutes: 10, cookMinutes: 25,
    ingredients: [
      { name: "Salmon fillets", quantity: "600 g" },
      { name: "Cherry tomatoes", quantity: "400 g" },
      { name: "Zucchini", quantity: "2" },
      { name: "Olives", quantity: "80 g" },
      { name: "Capers", quantity: "20 g" },
      { name: "Olive oil", quantity: "30 ml" },
      { name: "Lemon", quantity: "1" },
    ],
    steps: [
      "Slice zucchini and toss with tomatoes, olives, capers, olive oil and lemon slices.",
      "Roast at 220°C for 12 minutes.",
      "Nestle salmon on top; roast 10 more minutes.",
    ],
    nutrition: { calories: 460, protein: 36, carbs: 14, fat: 28 },
    allergens: ["Fish/Shellfish"],
  }),
  r({
    id: "med-gyros",
    title: "Chicken Gyros Bowl",
    cuisine: "Mediterranean", mealType: "dinner",
    prepMinutes: 15, cookMinutes: 15,
    ingredients: [
      { name: "Chicken breast", quantity: "600 g" },
      { name: "Greek yogurt", quantity: "300 g" },
      { name: "Cucumber", quantity: "1" },
      { name: "Garlic", quantity: "2 cloves" },
      { name: "Lemon", quantity: "1" },
      { name: "Olive oil", quantity: "30 ml" },
      { name: "Pita or rice", quantity: "500 g" },
      { name: "Cherry tomatoes", quantity: "200 g" },
      { name: "Dried oregano", quantity: "5 g" },
    ],
    steps: [
      "Marinate chicken in lemon, olive oil, garlic and oregano 15 minutes.",
      "Grate cucumber, squeeze dry, mix with yogurt and crushed garlic for tzatziki.",
      "Sear chicken 5 minutes per side; rest and slice.",
      "Serve over pita or rice with tomatoes and tzatziki.",
    ],
    nutrition: { calories: 580, protein: 42, carbs: 60, fat: 18 },
    allergens: ["Milk", "Gluten"],
  }),
  r({
    id: "med-stuffed-peppers",
    title: "Rice-stuffed Peppers",
    cuisine: "Mediterranean", mealType: "dinner",
    prepMinutes: 15, cookMinutes: 50,
    ingredients: [
      { name: "Bell peppers", quantity: "6" },
      { name: "Rice", quantity: "200 g" },
      { name: "Ground lamb or beef", quantity: "400 g" },
      { name: "Onion", quantity: "1" },
      { name: "Crushed tomatoes", quantity: "300 g" },
      { name: "Pine nuts", quantity: "30 g" },
      { name: "Olive oil", quantity: "30 ml" },
      { name: "Cinnamon", quantity: "to taste" },
    ],
    steps: [
      "Brown meat with onion and pine nuts 6 minutes. Stir in rice, tomatoes, cinnamon.",
      "Cut tops off peppers and remove seeds.",
      "Stuff peppers; place upright in a baking dish with 200 ml water.",
      "Bake covered at 190°C for 40 minutes; uncover for 10 minutes.",
    ],
    nutrition: { calories: 480, protein: 22, carbs: 56, fat: 18 },
  }),
  r({
    id: "med-tabbouleh",
    title: "Tabbouleh",
    cuisine: "Mediterranean", mealType: "lunch",
    prepMinutes: 20, cookMinutes: 5,
    ingredients: [
      { name: "Bulgur wheat", quantity: "150 g" },
      { name: "Parsley", quantity: "2 bunches" },
      { name: "Mint", quantity: "1 bunch" },
      { name: "Tomatoes", quantity: "300 g" },
      { name: "Cucumber", quantity: "1" },
      { name: "Lemon", quantity: "2" },
      { name: "Olive oil", quantity: "60 ml" },
    ],
    steps: [
      "Soak bulgur in 200 ml boiling water 15 minutes; fluff with a fork.",
      "Finely chop parsley, mint, tomatoes and cucumber.",
      "Combine everything with lemon juice and olive oil.",
      "Season and chill 10 minutes before serving.",
    ],
    nutrition: { calories: 260, protein: 6, carbs: 38, fat: 10 },
    allergens: ["Gluten"],
  }),
  r({
    id: "med-fish-baked",
    title: "Greek Baked Fish (Plaki)",
    cuisine: "Mediterranean", mealType: "dinner",
    prepMinutes: 10, cookMinutes: 30,
    ingredients: [
      { name: "White fish fillets", quantity: "700 g" },
      { name: "Tomatoes", quantity: "500 g" },
      { name: "Onion", quantity: "1" },
      { name: "Garlic", quantity: "3 cloves" },
      { name: "Olive oil", quantity: "50 ml" },
      { name: "Lemon", quantity: "1" },
      { name: "Parsley", quantity: "0.5 bunch" },
    ],
    steps: [
      "Sauté sliced onion and garlic in olive oil 6 minutes.",
      "Add diced tomatoes; simmer 8 minutes.",
      "Lay fish in a baking dish; spoon sauce over.",
      "Bake at 200°C for 15 minutes. Finish with lemon juice and parsley.",
    ],
    nutrition: { calories: 360, protein: 36, carbs: 12, fat: 16 },
    allergens: ["Fish/Shellfish"],
  }),
  r({
    id: "med-yogurt-honey",
    title: "Greek Yogurt with Honey & Nuts",
    cuisine: "Mediterranean", mealType: "breakfast",
    prepMinutes: 5, cookMinutes: 0,
    ingredients: [
      { name: "Greek yogurt", quantity: "600 g" },
      { name: "Honey", quantity: "80 g" },
      { name: "Walnuts", quantity: "100 g" },
      { name: "Berries", quantity: "200 g" },
    ],
    steps: [
      "Spoon yogurt into bowls.",
      "Drizzle generously with honey.",
      "Top with chopped walnuts and berries.",
    ],
    nutrition: { calories: 380, protein: 18, carbs: 36, fat: 18 },
    allergens: ["Milk", "Nuts"],
  }),
  r({
    id: "med-avocado-toast",
    title: "Avocado toast & poached egg",
    cuisine: "Mediterranean", mealType: "breakfast",
    prepMinutes: 10, cookMinutes: 8,
    ingredients: [
      { name: "Avocado", quantity: "2" },
      { name: "Sourdough bread", quantity: "8 slices" },
      { name: "Eggs", quantity: "4" },
      { name: "Lemon", quantity: "1" },
      { name: "Olive oil", quantity: "20 ml" },
      { name: "Chilli flakes", quantity: "5 g" },
    ],
    steps: [
      "Toast the sourdough until crisp and golden.",
      "Mash avocado with lemon juice, olive oil and a pinch of chilli flakes.",
      "Poach eggs in barely simmering water for 3 minutes until the whites set.",
      "Spread avocado on toast and top each serving with a poached egg.",
    ],
    nutrition: { calories: 420, protein: 16, carbs: 34, fat: 26 },
    allergens: ["Egg", "Gluten"],
    aliases: ["avocado toast", "avocado toast poached egg"],
  }),
  r({
    id: "med-lamb-tagine",
    title: "Lamb tagine",
    cuisine: "Mediterranean", mealType: "dinner",
    prepMinutes: 20, cookMinutes: 80, difficulty: "medium",
    ingredients: [
      { name: "Lamb shoulder", quantity: "800 g" },
      { name: "Onions", quantity: "2" },
      { name: "Carrots", quantity: "3" },
      { name: "Chickpeas", quantity: "400 g" },
      { name: "Chopped tomatoes", quantity: "400 g" },
      { name: "Dried apricots", quantity: "100 g" },
      { name: "Couscous", quantity: "300 g" },
      { name: "Mixed spices", quantity: "20 g" },
      { name: "Olive oil", quantity: "30 ml" },
    ],
    steps: [
      "Brown diced lamb in olive oil until deeply coloured on all sides.",
      "Soften onions and carrots in the same pan, then toast the spices until fragrant.",
      "Add tomatoes, chickpeas, apricots and enough water to barely cover; simmer gently until the lamb is tender.",
      "Steam couscous separately and serve it under the tagine sauce.",
    ],
    nutrition: { calories: 680, protein: 42, carbs: 62, fat: 28 },
    allergens: ["Gluten"],
    aliases: ["slow-cooked lamb tagine", "lamb tajine"],
  }),
];
